FROM eclipse-temurin:17
MAINTAINER junsong
RUN mkdir -p /home/junsong
WORKDIR /home/junsong
COPY ./jar/junsong-modules-open.jar /home/junsong/junsong-modules-open.jar
ENTRYPOINT ["java","-jar","junsong-modules-open.jar"]
