/*
 * 开放平台接口文档
 * 开放平台应用管理与API Key服务接口
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.junsong.open.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AjaxResult
 */
public class AjaxResultTest {
    private final AjaxResult model = new AjaxResult();

    /**
     * Model tests for AjaxResult
     */
    @Test
    public void testAjaxResult() {
        // TODO: test AjaxResult
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

    /**
     * Test the property 'success'
     */
    @Test
    public void successTest() {
        // TODO: test success
    }

    /**
     * Test the property 'warn'
     */
    @Test
    public void warnTest() {
        // TODO: test warn
    }

    /**
     * Test the property 'empty'
     */
    @Test
    public void emptyTest() {
        // TODO: test empty
    }

}
