/*
 * 开放平台接口文档
 * 开放平台应用管理与API Key服务接口
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.junsong.open.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OpenAppSecret
 */
public class OpenAppSecretTest {
    private final OpenAppSecret model = new OpenAppSecret();

    /**
     * Model tests for OpenAppSecret
     */
    @Test
    public void testOpenAppSecret() {
        // TODO: test OpenAppSecret
    }

    /**
     * Test the property 'createBy'
     */
    @Test
    public void createByTest() {
        // TODO: test createBy
    }

    /**
     * Test the property 'createTime'
     */
    @Test
    public void createTimeTest() {
        // TODO: test createTime
    }

    /**
     * Test the property 'updateBy'
     */
    @Test
    public void updateByTest() {
        // TODO: test updateBy
    }

    /**
     * Test the property 'updateTime'
     */
    @Test
    public void updateTimeTest() {
        // TODO: test updateTime
    }

    /**
     * Test the property 'remark'
     */
    @Test
    public void remarkTest() {
        // TODO: test remark
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'params'
     */
    @Test
    public void paramsTest() {
        // TODO: test params
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'appId'
     */
    @Test
    public void appIdTest() {
        // TODO: test appId
    }

    /**
     * Test the property 'appKey'
     */
    @Test
    public void appKeyTest() {
        // TODO: test appKey
    }

    /**
     * Test the property 'appSecret'
     */
    @Test
    public void appSecretTest() {
        // TODO: test appSecret
    }

    /**
     * Test the property 'keyType'
     */
    @Test
    public void keyTypeTest() {
        // TODO: test keyType
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'dailyQuota'
     */
    @Test
    public void dailyQuotaTest() {
        // TODO: test dailyQuota
    }

    /**
     * Test the property 'expireTime'
     */
    @Test
    public void expireTimeTest() {
        // TODO: test expireTime
    }

    /**
     * Test the property 'delFlag'
     */
    @Test
    public void delFlagTest() {
        // TODO: test delFlag
    }

}
