# coding: utf-8

"""
    开放平台接口文档

    开放平台应用管理与API Key服务接口

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class OpenApp(BaseModel):
    """
    OpenApp
    """ # noqa: E501
    create_by: Optional[StrictStr] = Field(default=None, alias="createBy")
    create_time: Optional[datetime] = Field(default=None, alias="createTime")
    update_by: Optional[StrictStr] = Field(default=None, alias="updateBy")
    update_time: Optional[datetime] = Field(default=None, alias="updateTime")
    remark: Optional[StrictStr] = None
    tenant_id: Optional[StrictInt] = Field(default=None, alias="tenantId")
    params: Optional[Dict[str, Any]] = None
    id: Optional[StrictInt] = None
    app_name: Optional[StrictStr] = Field(default=None, alias="appName")
    app_type: Optional[StrictStr] = Field(default=None, alias="appType")
    description: Optional[StrictStr] = None
    website_url: Optional[StrictStr] = Field(default=None, alias="websiteUrl")
    callback_url: Optional[StrictStr] = Field(default=None, alias="callbackUrl")
    contact_name: Optional[StrictStr] = Field(default=None, alias="contactName")
    contact_phone: Optional[StrictStr] = Field(default=None, alias="contactPhone")
    contact_email: Optional[StrictStr] = Field(default=None, alias="contactEmail")
    status: Optional[StrictStr] = None
    reject_reason: Optional[StrictStr] = Field(default=None, alias="rejectReason")
    del_flag: Optional[StrictStr] = Field(default=None, alias="delFlag")
    __properties: ClassVar[List[str]] = ["createBy", "createTime", "updateBy", "updateTime", "remark", "tenantId", "params", "id", "appName", "appType", "description", "websiteUrl", "callbackUrl", "contactName", "contactPhone", "contactEmail", "status", "rejectReason", "delFlag"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OpenApp from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OpenApp from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "createBy": obj.get("createBy"),
            "createTime": obj.get("createTime"),
            "updateBy": obj.get("updateBy"),
            "updateTime": obj.get("updateTime"),
            "remark": obj.get("remark"),
            "tenantId": obj.get("tenantId"),
            "params": obj.get("params"),
            "id": obj.get("id"),
            "appName": obj.get("appName"),
            "appType": obj.get("appType"),
            "description": obj.get("description"),
            "websiteUrl": obj.get("websiteUrl"),
            "callbackUrl": obj.get("callbackUrl"),
            "contactName": obj.get("contactName"),
            "contactPhone": obj.get("contactPhone"),
            "contactEmail": obj.get("contactEmail"),
            "status": obj.get("status"),
            "rejectReason": obj.get("rejectReason"),
            "delFlag": obj.get("delFlag")
        })
        return _obj


