/**
 * 开放平台接口文档
 * 开放平台应用管理与API Key服务接口
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AjaxResult from '../model/AjaxResult';
import OpenApp from '../model/OpenApp';
import OpenAppSecret from '../model/OpenAppSecret';
import TableDataInfo from '../model/TableDataInfo';

/**
* OpenAppController service.
* @module api/OpenAppControllerApi
* @version 1.0.0
*/
export default class OpenAppControllerApi {

    /**
    * Constructs a new OpenAppControllerApi. 
    * @alias module:api/OpenAppControllerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the add operation.
     * @callback module:api/OpenAppControllerApi~addCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AjaxResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/OpenApp} openApp 
     * @param {module:api/OpenAppControllerApi~addCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AjaxResult}
     */
    add(openApp, callback) {
      let postBody = openApp;
      // verify the required parameter 'openApp' is set
      if (openApp === undefined || openApp === null) {
        throw new Error("Missing the required parameter 'openApp' when calling add");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apikey'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = AjaxResult;
      return this.apiClient.callApi(
        '/app', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the approve operation.
     * @callback module:api/OpenAppControllerApi~approveCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AjaxResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} appId 
     * @param {module:api/OpenAppControllerApi~approveCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AjaxResult}
     */
    approve(appId, callback) {
      let postBody = null;
      // verify the required parameter 'appId' is set
      if (appId === undefined || appId === null) {
        throw new Error("Missing the required parameter 'appId' when calling approve");
      }

      let pathParams = {
        'appId': appId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apikey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = AjaxResult;
      return this.apiClient.callApi(
        '/app/approve/{appId}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the callExport operation.
     * @callback module:api/OpenAppControllerApi~callExportCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/OpenApp} openApp 
     * @param {module:api/OpenAppControllerApi~callExportCallback} callback The callback function, accepting three arguments: error, data, response
     */
    callExport(openApp, callback) {
      let postBody = null;
      // verify the required parameter 'openApp' is set
      if (openApp === undefined || openApp === null) {
        throw new Error("Missing the required parameter 'openApp' when calling callExport");
      }

      let pathParams = {
      };
      let queryParams = {
        'openApp': openApp
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apikey'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/app/export', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the changeKeyStatus operation.
     * @callback module:api/OpenAppControllerApi~changeKeyStatusCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AjaxResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/OpenAppSecret} openAppSecret 
     * @param {module:api/OpenAppControllerApi~changeKeyStatusCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AjaxResult}
     */
    changeKeyStatus(openAppSecret, callback) {
      let postBody = openAppSecret;
      // verify the required parameter 'openAppSecret' is set
      if (openAppSecret === undefined || openAppSecret === null) {
        throw new Error("Missing the required parameter 'openAppSecret' when calling changeKeyStatus");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apikey'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = AjaxResult;
      return this.apiClient.callApi(
        '/app/keys/changeStatus', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the edit operation.
     * @callback module:api/OpenAppControllerApi~editCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AjaxResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/OpenApp} openApp 
     * @param {module:api/OpenAppControllerApi~editCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AjaxResult}
     */
    edit(openApp, callback) {
      let postBody = openApp;
      // verify the required parameter 'openApp' is set
      if (openApp === undefined || openApp === null) {
        throw new Error("Missing the required parameter 'openApp' when calling edit");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apikey'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = AjaxResult;
      return this.apiClient.callApi(
        '/app', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getInfo operation.
     * @callback module:api/OpenAppControllerApi~getInfoCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AjaxResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:api/OpenAppControllerApi~getInfoCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AjaxResult}
     */
    getInfo(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getInfo");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apikey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = AjaxResult;
      return this.apiClient.callApi(
        '/app/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the list operation.
     * @callback module:api/OpenAppControllerApi~listCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TableDataInfo} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/OpenApp} openApp 
     * @param {module:api/OpenAppControllerApi~listCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TableDataInfo}
     */
    list(openApp, callback) {
      let postBody = null;
      // verify the required parameter 'openApp' is set
      if (openApp === undefined || openApp === null) {
        throw new Error("Missing the required parameter 'openApp' when calling list");
      }

      let pathParams = {
      };
      let queryParams = {
        'openApp': openApp
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apikey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = TableDataInfo;
      return this.apiClient.callApi(
        '/app/list', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the listAllKeys operation.
     * @callback module:api/OpenAppControllerApi~listAllKeysCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TableDataInfo} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/OpenAppSecret} openAppSecret 
     * @param {module:api/OpenAppControllerApi~listAllKeysCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TableDataInfo}
     */
    listAllKeys(openAppSecret, callback) {
      let postBody = null;
      // verify the required parameter 'openAppSecret' is set
      if (openAppSecret === undefined || openAppSecret === null) {
        throw new Error("Missing the required parameter 'openAppSecret' when calling listAllKeys");
      }

      let pathParams = {
      };
      let queryParams = {
        'openAppSecret': openAppSecret
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apikey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = TableDataInfo;
      return this.apiClient.callApi(
        '/app/keys/list', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the listKeys operation.
     * @callback module:api/OpenAppControllerApi~listKeysCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AjaxResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} appId 
     * @param {module:api/OpenAppControllerApi~listKeysCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AjaxResult}
     */
    listKeys(appId, callback) {
      let postBody = null;
      // verify the required parameter 'appId' is set
      if (appId === undefined || appId === null) {
        throw new Error("Missing the required parameter 'appId' when calling listKeys");
      }

      let pathParams = {
        'appId': appId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apikey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = AjaxResult;
      return this.apiClient.callApi(
        '/app/keys/{appId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the reject operation.
     * @callback module:api/OpenAppControllerApi~rejectCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AjaxResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} appId 
     * @param {String} rejectReason 
     * @param {module:api/OpenAppControllerApi~rejectCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AjaxResult}
     */
    reject(appId, rejectReason, callback) {
      let postBody = null;
      // verify the required parameter 'appId' is set
      if (appId === undefined || appId === null) {
        throw new Error("Missing the required parameter 'appId' when calling reject");
      }
      // verify the required parameter 'rejectReason' is set
      if (rejectReason === undefined || rejectReason === null) {
        throw new Error("Missing the required parameter 'rejectReason' when calling reject");
      }

      let pathParams = {
        'appId': appId
      };
      let queryParams = {
        'rejectReason': rejectReason
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apikey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = AjaxResult;
      return this.apiClient.callApi(
        '/app/reject/{appId}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the remove operation.
     * @callback module:api/OpenAppControllerApi~removeCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AjaxResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Array.<Number>} ids 
     * @param {module:api/OpenAppControllerApi~removeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AjaxResult}
     */
    remove(ids, callback) {
      let postBody = null;
      // verify the required parameter 'ids' is set
      if (ids === undefined || ids === null) {
        throw new Error("Missing the required parameter 'ids' when calling remove");
      }

      let pathParams = {
        'ids': ids
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apikey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = AjaxResult;
      return this.apiClient.callApi(
        '/app/{ids}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
