/**
 * 开放平台接口文档
 * 开放平台应用管理与API Key服务接口
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AjaxResult from '../model/AjaxResult';

/**
* OpenInternalController service.
* @module api/OpenInternalControllerApi
* @version 1.0.0
*/
export default class OpenInternalControllerApi {

    /**
    * Constructs a new OpenInternalControllerApi. 
    * @alias module:api/OpenInternalControllerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getByAppKey operation.
     * @callback module:api/OpenInternalControllerApi~getByAppKeyCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AjaxResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} appKey 
     * @param {module:api/OpenInternalControllerApi~getByAppKeyCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AjaxResult}
     */
    getByAppKey(appKey, callback) {
      let postBody = null;
      // verify the required parameter 'appKey' is set
      if (appKey === undefined || appKey === null) {
        throw new Error("Missing the required parameter 'appKey' when calling getByAppKey");
      }

      let pathParams = {
        'appKey': appKey
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apikey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = AjaxResult;
      return this.apiClient.callApi(
        '/internal/secret/byKey/{appKey}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
