# 基础镜像
FROM eclipse-temurin:17
# author
MAINTAINER junsong

# 挂载目录
VOLUME /home/junsong
# 创建目录
RUN mkdir -p /home/junsong
# 指定路径
WORKDIR /home/junsong
# 复制jar文件到路径
COPY ./jar/junsong-visual-monitor.jar /home/junsong/junsong-visual-monitor.jar
# 启动监控服务
ENTRYPOINT ["java","-jar","junsong-visual-monitor.jar"]