server:
  port: 8080

spring:
  application:
    name: junsong-gateway
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  cloud:
    nacos:
      discovery:
        server-addr: junsong-nacos:8848
        username: nacos
        password: ${NACOS_PASSWORD:nacos}
        enabled: true
      config:
        server-addr: junsong-nacos:8848
        username: nacos
        password: ${NACOS_PASSWORD:nacos}
        remote-first: false

springdoc:
  api-docs:
    enabled: false
