/**
 * 开放平台接口文档
 * 开放平台应用管理与API Key服务接口
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AjaxResult model module.
 * @module model/AjaxResult
 * @version 1.0.0
 */
class AjaxResult {
    /**
     * Constructs a new <code>AjaxResult</code>.
     * @alias module:model/AjaxResult
     * @extends Object
     */
    constructor() { 
        
        AjaxResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AjaxResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AjaxResult} obj Optional instance to populate.
     * @return {module:model/AjaxResult} The populated <code>AjaxResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AjaxResult();

            ApiClient.constructFromObject(data, obj, 'Object');
            

            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'Boolean');
            }
            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
            if (data.hasOwnProperty('warn')) {
                obj['warn'] = ApiClient.convertToType(data['warn'], 'Boolean');
            }
            if (data.hasOwnProperty('empty')) {
                obj['empty'] = ApiClient.convertToType(data['empty'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AjaxResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AjaxResult</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Boolean} error
 */
AjaxResult.prototype['error'] = undefined;

/**
 * @member {Boolean} success
 */
AjaxResult.prototype['success'] = undefined;

/**
 * @member {Boolean} warn
 */
AjaxResult.prototype['warn'] = undefined;

/**
 * @member {Boolean} empty
 */
AjaxResult.prototype['empty'] = undefined;






export default AjaxResult;

