/**
 * 开放平台接口文档
 * 开放平台应用管理与API Key服务接口
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OpenApp model module.
 * @module model/OpenApp
 * @version 1.0.0
 */
class OpenApp {
    /**
     * Constructs a new <code>OpenApp</code>.
     * @alias module:model/OpenApp
     */
    constructor() { 
        
        OpenApp.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OpenApp</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OpenApp} obj Optional instance to populate.
     * @return {module:model/OpenApp} The populated <code>OpenApp</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OpenApp();

            if (data.hasOwnProperty('createBy')) {
                obj['createBy'] = ApiClient.convertToType(data['createBy'], 'String');
            }
            if (data.hasOwnProperty('createTime')) {
                obj['createTime'] = ApiClient.convertToType(data['createTime'], 'Date');
            }
            if (data.hasOwnProperty('updateBy')) {
                obj['updateBy'] = ApiClient.convertToType(data['updateBy'], 'String');
            }
            if (data.hasOwnProperty('updateTime')) {
                obj['updateTime'] = ApiClient.convertToType(data['updateTime'], 'Date');
            }
            if (data.hasOwnProperty('remark')) {
                obj['remark'] = ApiClient.convertToType(data['remark'], 'String');
            }
            if (data.hasOwnProperty('tenantId')) {
                obj['tenantId'] = ApiClient.convertToType(data['tenantId'], 'Number');
            }
            if (data.hasOwnProperty('params')) {
                obj['params'] = ApiClient.convertToType(data['params'], {'String': Object});
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('appName')) {
                obj['appName'] = ApiClient.convertToType(data['appName'], 'String');
            }
            if (data.hasOwnProperty('appType')) {
                obj['appType'] = ApiClient.convertToType(data['appType'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('websiteUrl')) {
                obj['websiteUrl'] = ApiClient.convertToType(data['websiteUrl'], 'String');
            }
            if (data.hasOwnProperty('callbackUrl')) {
                obj['callbackUrl'] = ApiClient.convertToType(data['callbackUrl'], 'String');
            }
            if (data.hasOwnProperty('contactName')) {
                obj['contactName'] = ApiClient.convertToType(data['contactName'], 'String');
            }
            if (data.hasOwnProperty('contactPhone')) {
                obj['contactPhone'] = ApiClient.convertToType(data['contactPhone'], 'String');
            }
            if (data.hasOwnProperty('contactEmail')) {
                obj['contactEmail'] = ApiClient.convertToType(data['contactEmail'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('rejectReason')) {
                obj['rejectReason'] = ApiClient.convertToType(data['rejectReason'], 'String');
            }
            if (data.hasOwnProperty('delFlag')) {
                obj['delFlag'] = ApiClient.convertToType(data['delFlag'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OpenApp</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OpenApp</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['createBy'] && !(typeof data['createBy'] === 'string' || data['createBy'] instanceof String)) {
            throw new Error("Expected the field `createBy` to be a primitive type in the JSON string but got " + data['createBy']);
        }
        // ensure the json data is a string
        if (data['updateBy'] && !(typeof data['updateBy'] === 'string' || data['updateBy'] instanceof String)) {
            throw new Error("Expected the field `updateBy` to be a primitive type in the JSON string but got " + data['updateBy']);
        }
        // ensure the json data is a string
        if (data['remark'] && !(typeof data['remark'] === 'string' || data['remark'] instanceof String)) {
            throw new Error("Expected the field `remark` to be a primitive type in the JSON string but got " + data['remark']);
        }
        // ensure the json data is a string
        if (data['appName'] && !(typeof data['appName'] === 'string' || data['appName'] instanceof String)) {
            throw new Error("Expected the field `appName` to be a primitive type in the JSON string but got " + data['appName']);
        }
        // ensure the json data is a string
        if (data['appType'] && !(typeof data['appType'] === 'string' || data['appType'] instanceof String)) {
            throw new Error("Expected the field `appType` to be a primitive type in the JSON string but got " + data['appType']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['websiteUrl'] && !(typeof data['websiteUrl'] === 'string' || data['websiteUrl'] instanceof String)) {
            throw new Error("Expected the field `websiteUrl` to be a primitive type in the JSON string but got " + data['websiteUrl']);
        }
        // ensure the json data is a string
        if (data['callbackUrl'] && !(typeof data['callbackUrl'] === 'string' || data['callbackUrl'] instanceof String)) {
            throw new Error("Expected the field `callbackUrl` to be a primitive type in the JSON string but got " + data['callbackUrl']);
        }
        // ensure the json data is a string
        if (data['contactName'] && !(typeof data['contactName'] === 'string' || data['contactName'] instanceof String)) {
            throw new Error("Expected the field `contactName` to be a primitive type in the JSON string but got " + data['contactName']);
        }
        // ensure the json data is a string
        if (data['contactPhone'] && !(typeof data['contactPhone'] === 'string' || data['contactPhone'] instanceof String)) {
            throw new Error("Expected the field `contactPhone` to be a primitive type in the JSON string but got " + data['contactPhone']);
        }
        // ensure the json data is a string
        if (data['contactEmail'] && !(typeof data['contactEmail'] === 'string' || data['contactEmail'] instanceof String)) {
            throw new Error("Expected the field `contactEmail` to be a primitive type in the JSON string but got " + data['contactEmail']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['rejectReason'] && !(typeof data['rejectReason'] === 'string' || data['rejectReason'] instanceof String)) {
            throw new Error("Expected the field `rejectReason` to be a primitive type in the JSON string but got " + data['rejectReason']);
        }
        // ensure the json data is a string
        if (data['delFlag'] && !(typeof data['delFlag'] === 'string' || data['delFlag'] instanceof String)) {
            throw new Error("Expected the field `delFlag` to be a primitive type in the JSON string but got " + data['delFlag']);
        }

        return true;
    }


}



/**
 * @member {String} createBy
 */
OpenApp.prototype['createBy'] = undefined;

/**
 * @member {Date} createTime
 */
OpenApp.prototype['createTime'] = undefined;

/**
 * @member {String} updateBy
 */
OpenApp.prototype['updateBy'] = undefined;

/**
 * @member {Date} updateTime
 */
OpenApp.prototype['updateTime'] = undefined;

/**
 * @member {String} remark
 */
OpenApp.prototype['remark'] = undefined;

/**
 * @member {Number} tenantId
 */
OpenApp.prototype['tenantId'] = undefined;

/**
 * @member {Object.<String, Object>} params
 */
OpenApp.prototype['params'] = undefined;

/**
 * @member {Number} id
 */
OpenApp.prototype['id'] = undefined;

/**
 * @member {String} appName
 */
OpenApp.prototype['appName'] = undefined;

/**
 * @member {String} appType
 */
OpenApp.prototype['appType'] = undefined;

/**
 * @member {String} description
 */
OpenApp.prototype['description'] = undefined;

/**
 * @member {String} websiteUrl
 */
OpenApp.prototype['websiteUrl'] = undefined;

/**
 * @member {String} callbackUrl
 */
OpenApp.prototype['callbackUrl'] = undefined;

/**
 * @member {String} contactName
 */
OpenApp.prototype['contactName'] = undefined;

/**
 * @member {String} contactPhone
 */
OpenApp.prototype['contactPhone'] = undefined;

/**
 * @member {String} contactEmail
 */
OpenApp.prototype['contactEmail'] = undefined;

/**
 * @member {String} status
 */
OpenApp.prototype['status'] = undefined;

/**
 * @member {String} rejectReason
 */
OpenApp.prototype['rejectReason'] = undefined;

/**
 * @member {String} delFlag
 */
OpenApp.prototype['delFlag'] = undefined;






export default OpenApp;

