/**
 * 开放平台接口文档
 * 开放平台应用管理与API Key服务接口
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OpenAppSecret model module.
 * @module model/OpenAppSecret
 * @version 1.0.0
 */
class OpenAppSecret {
    /**
     * Constructs a new <code>OpenAppSecret</code>.
     * @alias module:model/OpenAppSecret
     */
    constructor() { 
        
        OpenAppSecret.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OpenAppSecret</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OpenAppSecret} obj Optional instance to populate.
     * @return {module:model/OpenAppSecret} The populated <code>OpenAppSecret</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OpenAppSecret();

            if (data.hasOwnProperty('createBy')) {
                obj['createBy'] = ApiClient.convertToType(data['createBy'], 'String');
            }
            if (data.hasOwnProperty('createTime')) {
                obj['createTime'] = ApiClient.convertToType(data['createTime'], 'Date');
            }
            if (data.hasOwnProperty('updateBy')) {
                obj['updateBy'] = ApiClient.convertToType(data['updateBy'], 'String');
            }
            if (data.hasOwnProperty('updateTime')) {
                obj['updateTime'] = ApiClient.convertToType(data['updateTime'], 'Date');
            }
            if (data.hasOwnProperty('remark')) {
                obj['remark'] = ApiClient.convertToType(data['remark'], 'String');
            }
            if (data.hasOwnProperty('tenantId')) {
                obj['tenantId'] = ApiClient.convertToType(data['tenantId'], 'Number');
            }
            if (data.hasOwnProperty('params')) {
                obj['params'] = ApiClient.convertToType(data['params'], {'String': Object});
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('appId')) {
                obj['appId'] = ApiClient.convertToType(data['appId'], 'Number');
            }
            if (data.hasOwnProperty('appKey')) {
                obj['appKey'] = ApiClient.convertToType(data['appKey'], 'String');
            }
            if (data.hasOwnProperty('appSecret')) {
                obj['appSecret'] = ApiClient.convertToType(data['appSecret'], 'String');
            }
            if (data.hasOwnProperty('keyType')) {
                obj['keyType'] = ApiClient.convertToType(data['keyType'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('dailyQuota')) {
                obj['dailyQuota'] = ApiClient.convertToType(data['dailyQuota'], 'Number');
            }
            if (data.hasOwnProperty('expireTime')) {
                obj['expireTime'] = ApiClient.convertToType(data['expireTime'], 'Date');
            }
            if (data.hasOwnProperty('delFlag')) {
                obj['delFlag'] = ApiClient.convertToType(data['delFlag'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OpenAppSecret</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OpenAppSecret</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['createBy'] && !(typeof data['createBy'] === 'string' || data['createBy'] instanceof String)) {
            throw new Error("Expected the field `createBy` to be a primitive type in the JSON string but got " + data['createBy']);
        }
        // ensure the json data is a string
        if (data['updateBy'] && !(typeof data['updateBy'] === 'string' || data['updateBy'] instanceof String)) {
            throw new Error("Expected the field `updateBy` to be a primitive type in the JSON string but got " + data['updateBy']);
        }
        // ensure the json data is a string
        if (data['remark'] && !(typeof data['remark'] === 'string' || data['remark'] instanceof String)) {
            throw new Error("Expected the field `remark` to be a primitive type in the JSON string but got " + data['remark']);
        }
        // ensure the json data is a string
        if (data['appKey'] && !(typeof data['appKey'] === 'string' || data['appKey'] instanceof String)) {
            throw new Error("Expected the field `appKey` to be a primitive type in the JSON string but got " + data['appKey']);
        }
        // ensure the json data is a string
        if (data['appSecret'] && !(typeof data['appSecret'] === 'string' || data['appSecret'] instanceof String)) {
            throw new Error("Expected the field `appSecret` to be a primitive type in the JSON string but got " + data['appSecret']);
        }
        // ensure the json data is a string
        if (data['keyType'] && !(typeof data['keyType'] === 'string' || data['keyType'] instanceof String)) {
            throw new Error("Expected the field `keyType` to be a primitive type in the JSON string but got " + data['keyType']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['delFlag'] && !(typeof data['delFlag'] === 'string' || data['delFlag'] instanceof String)) {
            throw new Error("Expected the field `delFlag` to be a primitive type in the JSON string but got " + data['delFlag']);
        }

        return true;
    }


}



/**
 * @member {String} createBy
 */
OpenAppSecret.prototype['createBy'] = undefined;

/**
 * @member {Date} createTime
 */
OpenAppSecret.prototype['createTime'] = undefined;

/**
 * @member {String} updateBy
 */
OpenAppSecret.prototype['updateBy'] = undefined;

/**
 * @member {Date} updateTime
 */
OpenAppSecret.prototype['updateTime'] = undefined;

/**
 * @member {String} remark
 */
OpenAppSecret.prototype['remark'] = undefined;

/**
 * @member {Number} tenantId
 */
OpenAppSecret.prototype['tenantId'] = undefined;

/**
 * @member {Object.<String, Object>} params
 */
OpenAppSecret.prototype['params'] = undefined;

/**
 * @member {Number} id
 */
OpenAppSecret.prototype['id'] = undefined;

/**
 * @member {Number} appId
 */
OpenAppSecret.prototype['appId'] = undefined;

/**
 * @member {String} appKey
 */
OpenAppSecret.prototype['appKey'] = undefined;

/**
 * @member {String} appSecret
 */
OpenAppSecret.prototype['appSecret'] = undefined;

/**
 * @member {String} keyType
 */
OpenAppSecret.prototype['keyType'] = undefined;

/**
 * @member {String} status
 */
OpenAppSecret.prototype['status'] = undefined;

/**
 * @member {Number} dailyQuota
 */
OpenAppSecret.prototype['dailyQuota'] = undefined;

/**
 * @member {Date} expireTime
 */
OpenAppSecret.prototype['expireTime'] = undefined;

/**
 * @member {String} delFlag
 */
OpenAppSecret.prototype['delFlag'] = undefined;






export default OpenAppSecret;

