/**
 * 开放平台接口文档
 * 开放平台应用管理与API Key服务接口
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AjaxResult from './model/AjaxResult';
import OpenApp from './model/OpenApp';
import OpenAppSecret from './model/OpenAppSecret';
import TableDataInfo from './model/TableDataInfo';
import OpenAppControllerApi from './api/OpenAppControllerApi';
import OpenInternalControllerApi from './api/OpenInternalControllerApi';


/**
* 开放平台应用管理与API Key服务接口.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var JunSongOpenApi = require('index'); // See note below*.
* var xxxSvc = new JunSongOpenApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new JunSongOpenApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new JunSongOpenApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new JunSongOpenApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AjaxResult model constructor.
     * @property {module:model/AjaxResult}
     */
    AjaxResult,

    /**
     * The OpenApp model constructor.
     * @property {module:model/OpenApp}
     */
    OpenApp,

    /**
     * The OpenAppSecret model constructor.
     * @property {module:model/OpenAppSecret}
     */
    OpenAppSecret,

    /**
     * The TableDataInfo model constructor.
     * @property {module:model/TableDataInfo}
     */
    TableDataInfo,

    /**
    * The OpenAppControllerApi service constructor.
    * @property {module:api/OpenAppControllerApi}
    */
    OpenAppControllerApi,

    /**
    * The OpenInternalControllerApi service constructor.
    * @property {module:api/OpenInternalControllerApi}
    */
    OpenInternalControllerApi
};
