# 基础镜像
FROM eclipse-temurin:17
# author
MAINTAINER junsong

# 挂载目录
VOLUME /home/junsong
# 创建目录
RUN mkdir -p /home/junsong
# 指定路径
WORKDIR /home/junsong
# 复制jar文件到路径
COPY ./jar/junsong-gateway.jar /home/junsong/junsong-gateway.jar
# 启动网关服务
ENTRYPOINT ["java","-jar","junsong-gateway.jar"]
