/**
 * 开放平台接口文档
 * 开放平台应用管理与API Key服务接口
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JunSongOpenApi);
  }
}(this, function(expect, JunSongOpenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JunSongOpenApi.AjaxResult();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AjaxResult', function() {
    it('should create an instance of AjaxResult', function() {
      // uncomment below and update the code to test AjaxResult
      //var instance = new JunSongOpenApi.AjaxResult();
      //expect(instance).to.be.a(JunSongOpenApi.AjaxResult);
    });

    it('should have the property error (base name: "error")', function() {
      // uncomment below and update the code to test the property error
      //var instance = new JunSongOpenApi.AjaxResult();
      //expect(instance).to.be();
    });

    it('should have the property success (base name: "success")', function() {
      // uncomment below and update the code to test the property success
      //var instance = new JunSongOpenApi.AjaxResult();
      //expect(instance).to.be();
    });

    it('should have the property warn (base name: "warn")', function() {
      // uncomment below and update the code to test the property warn
      //var instance = new JunSongOpenApi.AjaxResult();
      //expect(instance).to.be();
    });

    it('should have the property empty (base name: "empty")', function() {
      // uncomment below and update the code to test the property empty
      //var instance = new JunSongOpenApi.AjaxResult();
      //expect(instance).to.be();
    });

  });

}));
