/**
 * 开放平台接口文档
 * 开放平台应用管理与API Key服务接口
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JunSongOpenApi);
  }
}(this, function(expect, JunSongOpenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JunSongOpenApi.OpenApp();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OpenApp', function() {
    it('should create an instance of OpenApp', function() {
      // uncomment below and update the code to test OpenApp
      //var instance = new JunSongOpenApi.OpenApp();
      //expect(instance).to.be.a(JunSongOpenApi.OpenApp);
    });

    it('should have the property createBy (base name: "createBy")', function() {
      // uncomment below and update the code to test the property createBy
      //var instance = new JunSongOpenApi.OpenApp();
      //expect(instance).to.be();
    });

    it('should have the property createTime (base name: "createTime")', function() {
      // uncomment below and update the code to test the property createTime
      //var instance = new JunSongOpenApi.OpenApp();
      //expect(instance).to.be();
    });

    it('should have the property updateBy (base name: "updateBy")', function() {
      // uncomment below and update the code to test the property updateBy
      //var instance = new JunSongOpenApi.OpenApp();
      //expect(instance).to.be();
    });

    it('should have the property updateTime (base name: "updateTime")', function() {
      // uncomment below and update the code to test the property updateTime
      //var instance = new JunSongOpenApi.OpenApp();
      //expect(instance).to.be();
    });

    it('should have the property remark (base name: "remark")', function() {
      // uncomment below and update the code to test the property remark
      //var instance = new JunSongOpenApi.OpenApp();
      //expect(instance).to.be();
    });

    it('should have the property tenantId (base name: "tenantId")', function() {
      // uncomment below and update the code to test the property tenantId
      //var instance = new JunSongOpenApi.OpenApp();
      //expect(instance).to.be();
    });

    it('should have the property params (base name: "params")', function() {
      // uncomment below and update the code to test the property params
      //var instance = new JunSongOpenApi.OpenApp();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new JunSongOpenApi.OpenApp();
      //expect(instance).to.be();
    });

    it('should have the property appName (base name: "appName")', function() {
      // uncomment below and update the code to test the property appName
      //var instance = new JunSongOpenApi.OpenApp();
      //expect(instance).to.be();
    });

    it('should have the property appType (base name: "appType")', function() {
      // uncomment below and update the code to test the property appType
      //var instance = new JunSongOpenApi.OpenApp();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new JunSongOpenApi.OpenApp();
      //expect(instance).to.be();
    });

    it('should have the property websiteUrl (base name: "websiteUrl")', function() {
      // uncomment below and update the code to test the property websiteUrl
      //var instance = new JunSongOpenApi.OpenApp();
      //expect(instance).to.be();
    });

    it('should have the property callbackUrl (base name: "callbackUrl")', function() {
      // uncomment below and update the code to test the property callbackUrl
      //var instance = new JunSongOpenApi.OpenApp();
      //expect(instance).to.be();
    });

    it('should have the property contactName (base name: "contactName")', function() {
      // uncomment below and update the code to test the property contactName
      //var instance = new JunSongOpenApi.OpenApp();
      //expect(instance).to.be();
    });

    it('should have the property contactPhone (base name: "contactPhone")', function() {
      // uncomment below and update the code to test the property contactPhone
      //var instance = new JunSongOpenApi.OpenApp();
      //expect(instance).to.be();
    });

    it('should have the property contactEmail (base name: "contactEmail")', function() {
      // uncomment below and update the code to test the property contactEmail
      //var instance = new JunSongOpenApi.OpenApp();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new JunSongOpenApi.OpenApp();
      //expect(instance).to.be();
    });

    it('should have the property rejectReason (base name: "rejectReason")', function() {
      // uncomment below and update the code to test the property rejectReason
      //var instance = new JunSongOpenApi.OpenApp();
      //expect(instance).to.be();
    });

    it('should have the property delFlag (base name: "delFlag")', function() {
      // uncomment below and update the code to test the property delFlag
      //var instance = new JunSongOpenApi.OpenApp();
      //expect(instance).to.be();
    });

  });

}));
