/**
 * 开放平台接口文档
 * 开放平台应用管理与API Key服务接口
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JunSongOpenApi);
  }
}(this, function(expect, JunSongOpenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JunSongOpenApi.OpenAppSecret();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OpenAppSecret', function() {
    it('should create an instance of OpenAppSecret', function() {
      // uncomment below and update the code to test OpenAppSecret
      //var instance = new JunSongOpenApi.OpenAppSecret();
      //expect(instance).to.be.a(JunSongOpenApi.OpenAppSecret);
    });

    it('should have the property createBy (base name: "createBy")', function() {
      // uncomment below and update the code to test the property createBy
      //var instance = new JunSongOpenApi.OpenAppSecret();
      //expect(instance).to.be();
    });

    it('should have the property createTime (base name: "createTime")', function() {
      // uncomment below and update the code to test the property createTime
      //var instance = new JunSongOpenApi.OpenAppSecret();
      //expect(instance).to.be();
    });

    it('should have the property updateBy (base name: "updateBy")', function() {
      // uncomment below and update the code to test the property updateBy
      //var instance = new JunSongOpenApi.OpenAppSecret();
      //expect(instance).to.be();
    });

    it('should have the property updateTime (base name: "updateTime")', function() {
      // uncomment below and update the code to test the property updateTime
      //var instance = new JunSongOpenApi.OpenAppSecret();
      //expect(instance).to.be();
    });

    it('should have the property remark (base name: "remark")', function() {
      // uncomment below and update the code to test the property remark
      //var instance = new JunSongOpenApi.OpenAppSecret();
      //expect(instance).to.be();
    });

    it('should have the property tenantId (base name: "tenantId")', function() {
      // uncomment below and update the code to test the property tenantId
      //var instance = new JunSongOpenApi.OpenAppSecret();
      //expect(instance).to.be();
    });

    it('should have the property params (base name: "params")', function() {
      // uncomment below and update the code to test the property params
      //var instance = new JunSongOpenApi.OpenAppSecret();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new JunSongOpenApi.OpenAppSecret();
      //expect(instance).to.be();
    });

    it('should have the property appId (base name: "appId")', function() {
      // uncomment below and update the code to test the property appId
      //var instance = new JunSongOpenApi.OpenAppSecret();
      //expect(instance).to.be();
    });

    it('should have the property appKey (base name: "appKey")', function() {
      // uncomment below and update the code to test the property appKey
      //var instance = new JunSongOpenApi.OpenAppSecret();
      //expect(instance).to.be();
    });

    it('should have the property appSecret (base name: "appSecret")', function() {
      // uncomment below and update the code to test the property appSecret
      //var instance = new JunSongOpenApi.OpenAppSecret();
      //expect(instance).to.be();
    });

    it('should have the property keyType (base name: "keyType")', function() {
      // uncomment below and update the code to test the property keyType
      //var instance = new JunSongOpenApi.OpenAppSecret();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new JunSongOpenApi.OpenAppSecret();
      //expect(instance).to.be();
    });

    it('should have the property dailyQuota (base name: "dailyQuota")', function() {
      // uncomment below and update the code to test the property dailyQuota
      //var instance = new JunSongOpenApi.OpenAppSecret();
      //expect(instance).to.be();
    });

    it('should have the property expireTime (base name: "expireTime")', function() {
      // uncomment below and update the code to test the property expireTime
      //var instance = new JunSongOpenApi.OpenAppSecret();
      //expect(instance).to.be();
    });

    it('should have the property delFlag (base name: "delFlag")', function() {
      // uncomment below and update the code to test the property delFlag
      //var instance = new JunSongOpenApi.OpenAppSecret();
      //expect(instance).to.be();
    });

  });

}));
