/**
 * 开放平台接口文档
 * 开放平台应用管理与API Key服务接口
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JunSongOpenApi);
  }
}(this, function(expect, JunSongOpenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JunSongOpenApi.TableDataInfo();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TableDataInfo', function() {
    it('should create an instance of TableDataInfo', function() {
      // uncomment below and update the code to test TableDataInfo
      //var instance = new JunSongOpenApi.TableDataInfo();
      //expect(instance).to.be.a(JunSongOpenApi.TableDataInfo);
    });

    it('should have the property total (base name: "total")', function() {
      // uncomment below and update the code to test the property total
      //var instance = new JunSongOpenApi.TableDataInfo();
      //expect(instance).to.be();
    });

    it('should have the property rows (base name: "rows")', function() {
      // uncomment below and update the code to test the property rows
      //var instance = new JunSongOpenApi.TableDataInfo();
      //expect(instance).to.be();
    });

    it('should have the property code (base name: "code")', function() {
      // uncomment below and update the code to test the property code
      //var instance = new JunSongOpenApi.TableDataInfo();
      //expect(instance).to.be();
    });

    it('should have the property msg (base name: "msg")', function() {
      // uncomment below and update the code to test the property msg
      //var instance = new JunSongOpenApi.TableDataInfo();
      //expect(instance).to.be();
    });

  });

}));
