# 基础镜像
FROM nginx
# author
MAINTAINER junsong

# 挂载目录
VOLUME /home/junsong/projects/junsong-ui
# 创建目录
RUN mkdir -p /home/junsong/projects/junsong-ui
# 指定路径
WORKDIR /home/junsong/projects/junsong-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/junsong/projects/junsong-ui
