/*
 * 开放平台接口文档
 * 开放平台应用管理与API Key服务接口
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.junsong.open.api;

import com.junsong.open.ApiException;
import com.junsong.open.model.AjaxResult;
import com.junsong.open.model.OpenApp;
import com.junsong.open.model.OpenAppSecret;
import com.junsong.open.model.TableDataInfo;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OpenAppControllerApi
 */
@Disabled
public class OpenAppControllerApiTest {

    private final OpenAppControllerApi api = new OpenAppControllerApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addTest() throws ApiException {
        OpenApp openApp = null;
        AjaxResult response = api.add(openApp);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void approveTest() throws ApiException {
        Long appId = null;
        AjaxResult response = api.approve(appId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void callListTest() throws ApiException {
        OpenApp openApp = null;
        TableDataInfo response = api.callList(openApp);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void changeKeyStatusTest() throws ApiException {
        OpenAppSecret openAppSecret = null;
        AjaxResult response = api.changeKeyStatus(openAppSecret);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void editTest() throws ApiException {
        OpenApp openApp = null;
        AjaxResult response = api.edit(openApp);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void exportTest() throws ApiException {
        OpenApp openApp = null;
        api.export(openApp);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getInfoTest() throws ApiException {
        Long id = null;
        AjaxResult response = api.getInfo(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listAllKeysTest() throws ApiException {
        OpenAppSecret openAppSecret = null;
        TableDataInfo response = api.listAllKeys(openAppSecret);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listKeysTest() throws ApiException {
        Long appId = null;
        AjaxResult response = api.listKeys(appId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void rejectTest() throws ApiException {
        Long appId = null;
        String rejectReason = null;
        AjaxResult response = api.reject(appId, rejectReason);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeTest() throws ApiException {
        List<Long> ids = null;
        AjaxResult response = api.remove(ids);
        // TODO: test validations
    }

}
