/*
 * 开放平台接口文档
 * 开放平台应用管理与API Key服务接口
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.junsong.open.api;

import com.junsong.open.ApiException;
import com.junsong.open.model.AjaxResult;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OpenInternalControllerApi
 */
@Disabled
public class OpenInternalControllerApiTest {

    private final OpenInternalControllerApi api = new OpenInternalControllerApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getByAppKeyTest() throws ApiException {
        String appKey = null;
        AjaxResult response = api.getByAppKey(appKey);
        // TODO: test validations
    }

}
