<template>
  <view class="page"><view class="hero"><text class="eyebrow">库存与成本</text><text class="title">{{ productName || '商品' }} · 库存流水</text><text class="note">{{ currentDeptName }}</text></view><scroll-view scroll-y class="scroll"><view v-for="row in rows" :key="row.ledgerId || row.id" class="card"><view class="head"><text>{{ changeTypeText(row.changeType || row.change_type) }}</text><text :class="Number(row.changeQuantity ?? row.change_quantity ?? 0) >= 0 ? 'in' : 'out'">{{ row.changeQuantity ?? row.change_quantity ?? 0 }}</text></view><view class="meta"><text>{{ row.createTime || row.create_time || '-' }}</text><text>余额 {{ row.afterQuantity ?? row.after_quantity ?? 0 }}</text></view><view class="remark">{{ row.remark || row.referenceNo || row.reference_no || row.referenceType || row.reference_type || '-' }}</view></view><view v-if="!loading && !rows.length" class="empty">暂无库存流水</view><view v-if="loading" class="empty">加载中</view></scroll-view></view>
</template>
<script>
import { queryStockLedger } from '@/api/stocktake.js'
import { request } from '@/api/index.js'
import { workContext } from '@/utils/workContext.js'
import { dictCache } from '@/utils/dictCache.js'
export default { data() { return { productId: null, productName: '', rows: [], loading: false, currentDeptName: '', adjustmentDict: [] } }, onLoad(options = {}) { const s = workContext.snapshot(); this.productId = options.productId || ''; this.productName = decodeURIComponent(options.productName || ''); this.currentDeptName = s.currentDept?.name || ''; if (!this.productId || !s.currentDeptId) return uni.showToast({ title: '缺少商品或部门信息', icon: 'none' }); if (options.deptId && String(options.deptId) !== String(s.currentDeptId)) return uni.showToast({ title: '部门范围已变化', icon: 'none' }); this.load() }, methods: { async loadDict() { try { this.adjustmentDict = await dictCache.get('finance_stock_adjustment_type', async () => { const res = await request({ url: '/system/dict/data/type/finance_stock_adjustment_type', method: 'GET' }); return res.data || res.rows || [] }) } catch (e) { this.adjustmentDict = [] } }, changeTypeText(type) { const item = this.adjustmentDict.find(x => String(x.dictValue ?? x.value) === String(type)); if (item) return item.dictLabel || item.label || type; return ({ PURCHASE_IN: '采购入库', PURCHASE_REVERSE: '采购冲销', SALE_OUT: '销售出库', SALE_REVERSE: '销售冲销', STOCK_INIT: '期初库存', OPENING_STOCK: '期初库存', HISTORY_REPLENISH: '历史数据补录', TRIAL_CONSUMPTION: '试用消耗', STORE_USE: '店面自用', DAMAGE_LOSS: '报损', OTHER: '其他', STOCK_ADJUSTMENT: '库存调整', ADJUSTMENT_IN: '库存调整入库', ADJUSTMENT_OUT: '库存调整出库', STOCK_TAKE_GAIN: '盘点盘盈', STOCK_TAKE_LOSS: '盘点盘亏', STOCK_TAKE_REVERSE: '盘点冲销' })[type] || type || '库存变动' }, async load() { this.loading = true; try { await this.loadDict(); const res = await queryStockLedger({ deptId: workContext.snapshot().currentDeptId, productId: this.productId, startDate: '2000-01-01', endDate: new Date().toISOString().slice(0, 10), pageNum: 1, pageSize: 100 }); const data = res.data || res; this.rows = data.rows || data.records || data.items || [] } catch (e) { uni.showToast({ title: e.msg || '库存流水加载失败', icon: 'none' }) } finally { this.loading = false } } } }
</script>
<style scoped>.page{min-height:100vh;background:#f5f7fb}.hero{padding:34rpx 28rpx;background:#087cf0;color:#fff}.eyebrow{display:block;font-size:23rpx;opacity:.8}.title{display:block;margin-top:10rpx;font-size:36rpx;font-weight:700}.note{display:block;margin-top:10rpx;font-size:23rpx;opacity:.85}.scroll{height:calc(100vh - 180rpx);padding:22rpx 24rpx;box-sizing:border-box}.card{background:#fff;border-radius:16rpx;padding:24rpx;margin-bottom:16rpx}.head,.meta{display:flex;justify-content:space-between}.head{font-size:28rpx;font-weight:600}.in{color:#16834b}.out{color:#c2410c}.meta,.remark{margin-top:14rpx;color:#718096;font-size:23rpx}.empty{text-align:center;padding:100rpx 0;color:#94a3b8;font-size:26rpx}</style>
