# 基础镜像
FROM eclipse-temurin:17
# author
MAINTAINER junsong

# 创建目录
RUN mkdir -p /home/junsong
# 指定路径
WORKDIR /home/junsong
# 复制jar文件到路径
COPY ./jar/junsong-auth.jar /home/junsong/junsong-auth.jar
# 启动认证服务
ENTRYPOINT ["java","-jar","junsong-auth.jar"]