import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const read = file => fs.readFileSync(path.join(root, file), 'utf8')

const periodPage = read('junsong-ui-v3/src/views/finance/accountingPeriod/index.vue')
const mpPermissionPage = read('junsong-ui-v3/src/views/member/mpPerm/index.vue')
const legacyModuleSql = read('sql/finance_remove_legacy_cost_accounting_module.sql')
const legacyMenuSql = read('sql/finance_remove_legacy_cost_accounting_menu.sql')
const crossPeriodTest = read('junsong-modules/junsong-finance/src/test/java/com/junsong/finance/service/impl/FinSalePaymentCrossPeriodTest.java')
const verificationService = read('junsong-modules/junsong-finance/src/main/java/com/junsong/finance/service/impl/FinExpenseVerificationServiceImpl.java')
const verificationPage = read('junsong-ui-v3/src/views/finance/verificationRecord/index.vue')
const periodCheckService = read('junsong-modules/junsong-finance/src/main/java/com/junsong/finance/service/impl/AccountingPeriodCheckServiceImpl.java')
const reportService = read('junsong-modules/junsong-finance/src/main/java/com/junsong/finance/service/impl/FinanceReportServiceImpl.java')
const expenseMapper = read('junsong-modules/junsong-finance/src/main/resources/mapper/finance/FinExpenseMapper.xml')
const profitShareMapper = read('junsong-modules/junsong-finance/src/main/resources/mapper/finance/FinProfitShareRecordMapper.xml')
const saleReportMapper = read('junsong-modules/junsong-finance/src/main/resources/mapper/finance/FinSaleReportMapper.xml')
const saleReportJava = read('junsong-modules/junsong-finance/src/main/java/com/junsong/finance/mapper/FinSaleReportMapper.java')
const periodFilter = read('junsong-ui-v3/src/components/finance/AccountingPeriodFilter.vue')
const salePage = read('junsong-ui-v3/src/views/finance/report/sale.vue')
const profitPage = read('junsong-ui-v3/src/views/finance/report/profit.vue')
const expensePage = read('junsong-ui-v3/src/views/finance/report/expense.vue')
const profitSharePage = read('junsong-ui-v3/src/views/finance/report/profitShare.vue')
const restoreMenusSql = read('sql/finance_restore_report_menus.sql')

assert.match(periodPage, /实际缴款收入/)
assert.match(periodPage, /周期成本（已核销费用\+进货\+未核销借支）/)
assert.match(periodPage, /历史销售欠款不会回写原销售周期/)
assert.match(periodPage, /历史欠款回收/)
assert.match(periodPage, /isHistoricalPayment/)
assert.doesNotMatch(mpPermissionPage, /key:\s*["']costAccounting["']/)
assert.match(legacyMenuSql, /finance:costAccounting:/)
assert.match(legacyModuleSql, /module_key\s*=\s*'costAccounting'/)
assert.match(crossPeriodTest, /当前核算周期|current period|currentPeriod/i)
assert.match(verificationService, /RELATION_SURPLUS|RELATION_SUPPLEMENT/)
assert.match(verificationPage, /原始借支/)
assert.match(verificationPage, /补款/)
assert.match(verificationPage, /节余/)
assert.match(periodCheckService, /"BLOCK"/)
assert.match(periodCheckService, /"WARNING"/)
assert.match(periodCheckService, /"INFO"/)
assert.match(periodCheckService, /UNSETTLED_RECEIVABLE/)
assert.match(reportService, /map\.put\("periodId", params\.getPeriodId\(\)\)/)
assert.ok((expenseMapper.match(/periodId != null/g) || []).length >= 4)
assert.ok((profitShareMapper.match(/periodId != null/g) || []).length >= 6)
assert.match(saleReportJava, /Map<String, Object> params/)
assert.ok((saleReportMapper.match(/period_id/g) || []).length >= 1)
assert.match(saleReportMapper, /periodId != null/)
assert.match(reportService, /finSaleReportMapper\.selectSaleTrendStats/)
assert.match(reportService, /finSaleReportMapper\.selectMemberSales/)
assert.match(reportService, /finSaleReportMapper\.selectSeckillSales/)
assert.match(reportService, /finSaleReportMapper\.selectSalesByDept/)
assert.match(reportService, /finSaleReportMapper\.selectProductSalesRank/)
assert.match(periodFilter, /listAccountingPeriod/)
assert.match(periodFilter, /authorizedDeptIds/)
assert.match(periodFilter, /deptNames/)
assert.match(periodFilter, /deptName.*period\.deptId|period\.deptId.*deptName/)
for (const page of [salePage, profitPage, expensePage, profitSharePage]) {
  assert.match(page, /AccountingPeriodFilter/)
  assert.match(page, /periodId/)
}
assert.match(restoreMenusSql, /finance:report:sale/)
assert.match(restoreMenusSql, /visible = '0'/)

console.log('finance accounting period evolution checks passed')
