/*
 * 开放平台接口文档
 * 开放平台应用管理与API Key服务接口
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.junsong.open.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.junsong.open.JSON;

/**
 * OpenAppSecret
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class OpenAppSecret {
  public static final String SERIALIZED_NAME_CREATE_BY = "createBy";
  @SerializedName(SERIALIZED_NAME_CREATE_BY)
  @javax.annotation.Nullable
  private String createBy;

  public static final String SERIALIZED_NAME_CREATE_TIME = "createTime";
  @SerializedName(SERIALIZED_NAME_CREATE_TIME)
  @javax.annotation.Nullable
  private OffsetDateTime createTime;

  public static final String SERIALIZED_NAME_UPDATE_BY = "updateBy";
  @SerializedName(SERIALIZED_NAME_UPDATE_BY)
  @javax.annotation.Nullable
  private String updateBy;

  public static final String SERIALIZED_NAME_UPDATE_TIME = "updateTime";
  @SerializedName(SERIALIZED_NAME_UPDATE_TIME)
  @javax.annotation.Nullable
  private OffsetDateTime updateTime;

  public static final String SERIALIZED_NAME_REMARK = "remark";
  @SerializedName(SERIALIZED_NAME_REMARK)
  @javax.annotation.Nullable
  private String remark;

  public static final String SERIALIZED_NAME_TENANT_ID = "tenantId";
  @SerializedName(SERIALIZED_NAME_TENANT_ID)
  @javax.annotation.Nullable
  private Long tenantId;

  public static final String SERIALIZED_NAME_PARAMS = "params";
  @SerializedName(SERIALIZED_NAME_PARAMS)
  @javax.annotation.Nullable
  private Map<String, Object> params = new HashMap<>();

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private Long id;

  public static final String SERIALIZED_NAME_APP_ID = "appId";
  @SerializedName(SERIALIZED_NAME_APP_ID)
  @javax.annotation.Nullable
  private Long appId;

  public static final String SERIALIZED_NAME_APP_KEY = "appKey";
  @SerializedName(SERIALIZED_NAME_APP_KEY)
  @javax.annotation.Nullable
  private String appKey;

  public static final String SERIALIZED_NAME_APP_SECRET = "appSecret";
  @SerializedName(SERIALIZED_NAME_APP_SECRET)
  @javax.annotation.Nullable
  private String appSecret;

  public static final String SERIALIZED_NAME_KEY_TYPE = "keyType";
  @SerializedName(SERIALIZED_NAME_KEY_TYPE)
  @javax.annotation.Nullable
  private String keyType;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private String status;

  public static final String SERIALIZED_NAME_DAILY_QUOTA = "dailyQuota";
  @SerializedName(SERIALIZED_NAME_DAILY_QUOTA)
  @javax.annotation.Nullable
  private Integer dailyQuota;

  public static final String SERIALIZED_NAME_EXPIRE_TIME = "expireTime";
  @SerializedName(SERIALIZED_NAME_EXPIRE_TIME)
  @javax.annotation.Nullable
  private OffsetDateTime expireTime;

  public static final String SERIALIZED_NAME_DEL_FLAG = "delFlag";
  @SerializedName(SERIALIZED_NAME_DEL_FLAG)
  @javax.annotation.Nullable
  private String delFlag;

  public OpenAppSecret() {
  }

  public OpenAppSecret createBy(@javax.annotation.Nullable String createBy) {
    this.createBy = createBy;
    return this;
  }

  /**
   * Get createBy
   * @return createBy
   */
  @javax.annotation.Nullable
  public String getCreateBy() {
    return createBy;
  }

  public void setCreateBy(@javax.annotation.Nullable String createBy) {
    this.createBy = createBy;
  }


  public OpenAppSecret createTime(@javax.annotation.Nullable OffsetDateTime createTime) {
    this.createTime = createTime;
    return this;
  }

  /**
   * Get createTime
   * @return createTime
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCreateTime() {
    return createTime;
  }

  public void setCreateTime(@javax.annotation.Nullable OffsetDateTime createTime) {
    this.createTime = createTime;
  }


  public OpenAppSecret updateBy(@javax.annotation.Nullable String updateBy) {
    this.updateBy = updateBy;
    return this;
  }

  /**
   * Get updateBy
   * @return updateBy
   */
  @javax.annotation.Nullable
  public String getUpdateBy() {
    return updateBy;
  }

  public void setUpdateBy(@javax.annotation.Nullable String updateBy) {
    this.updateBy = updateBy;
  }


  public OpenAppSecret updateTime(@javax.annotation.Nullable OffsetDateTime updateTime) {
    this.updateTime = updateTime;
    return this;
  }

  /**
   * Get updateTime
   * @return updateTime
   */
  @javax.annotation.Nullable
  public OffsetDateTime getUpdateTime() {
    return updateTime;
  }

  public void setUpdateTime(@javax.annotation.Nullable OffsetDateTime updateTime) {
    this.updateTime = updateTime;
  }


  public OpenAppSecret remark(@javax.annotation.Nullable String remark) {
    this.remark = remark;
    return this;
  }

  /**
   * Get remark
   * @return remark
   */
  @javax.annotation.Nullable
  public String getRemark() {
    return remark;
  }

  public void setRemark(@javax.annotation.Nullable String remark) {
    this.remark = remark;
  }


  public OpenAppSecret tenantId(@javax.annotation.Nullable Long tenantId) {
    this.tenantId = tenantId;
    return this;
  }

  /**
   * Get tenantId
   * @return tenantId
   */
  @javax.annotation.Nullable
  public Long getTenantId() {
    return tenantId;
  }

  public void setTenantId(@javax.annotation.Nullable Long tenantId) {
    this.tenantId = tenantId;
  }


  public OpenAppSecret params(@javax.annotation.Nullable Map<String, Object> params) {
    this.params = params;
    return this;
  }

  public OpenAppSecret putParamsItem(String key, Object paramsItem) {
    if (this.params == null) {
      this.params = new HashMap<>();
    }
    this.params.put(key, paramsItem);
    return this;
  }

  /**
   * Get params
   * @return params
   */
  @javax.annotation.Nullable
  public Map<String, Object> getParams() {
    return params;
  }

  public void setParams(@javax.annotation.Nullable Map<String, Object> params) {
    this.params = params;
  }


  public OpenAppSecret id(@javax.annotation.Nullable Long id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public Long getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable Long id) {
    this.id = id;
  }


  public OpenAppSecret appId(@javax.annotation.Nullable Long appId) {
    this.appId = appId;
    return this;
  }

  /**
   * Get appId
   * @return appId
   */
  @javax.annotation.Nullable
  public Long getAppId() {
    return appId;
  }

  public void setAppId(@javax.annotation.Nullable Long appId) {
    this.appId = appId;
  }


  public OpenAppSecret appKey(@javax.annotation.Nullable String appKey) {
    this.appKey = appKey;
    return this;
  }

  /**
   * Get appKey
   * @return appKey
   */
  @javax.annotation.Nullable
  public String getAppKey() {
    return appKey;
  }

  public void setAppKey(@javax.annotation.Nullable String appKey) {
    this.appKey = appKey;
  }


  public OpenAppSecret appSecret(@javax.annotation.Nullable String appSecret) {
    this.appSecret = appSecret;
    return this;
  }

  /**
   * Get appSecret
   * @return appSecret
   */
  @javax.annotation.Nullable
  public String getAppSecret() {
    return appSecret;
  }

  public void setAppSecret(@javax.annotation.Nullable String appSecret) {
    this.appSecret = appSecret;
  }


  public OpenAppSecret keyType(@javax.annotation.Nullable String keyType) {
    this.keyType = keyType;
    return this;
  }

  /**
   * Get keyType
   * @return keyType
   */
  @javax.annotation.Nullable
  public String getKeyType() {
    return keyType;
  }

  public void setKeyType(@javax.annotation.Nullable String keyType) {
    this.keyType = keyType;
  }


  public OpenAppSecret status(@javax.annotation.Nullable String status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  public String getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable String status) {
    this.status = status;
  }


  public OpenAppSecret dailyQuota(@javax.annotation.Nullable Integer dailyQuota) {
    this.dailyQuota = dailyQuota;
    return this;
  }

  /**
   * Get dailyQuota
   * @return dailyQuota
   */
  @javax.annotation.Nullable
  public Integer getDailyQuota() {
    return dailyQuota;
  }

  public void setDailyQuota(@javax.annotation.Nullable Integer dailyQuota) {
    this.dailyQuota = dailyQuota;
  }


  public OpenAppSecret expireTime(@javax.annotation.Nullable OffsetDateTime expireTime) {
    this.expireTime = expireTime;
    return this;
  }

  /**
   * Get expireTime
   * @return expireTime
   */
  @javax.annotation.Nullable
  public OffsetDateTime getExpireTime() {
    return expireTime;
  }

  public void setExpireTime(@javax.annotation.Nullable OffsetDateTime expireTime) {
    this.expireTime = expireTime;
  }


  public OpenAppSecret delFlag(@javax.annotation.Nullable String delFlag) {
    this.delFlag = delFlag;
    return this;
  }

  /**
   * Get delFlag
   * @return delFlag
   */
  @javax.annotation.Nullable
  public String getDelFlag() {
    return delFlag;
  }

  public void setDelFlag(@javax.annotation.Nullable String delFlag) {
    this.delFlag = delFlag;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OpenAppSecret openAppSecret = (OpenAppSecret) o;
    return Objects.equals(this.createBy, openAppSecret.createBy) &&
        Objects.equals(this.createTime, openAppSecret.createTime) &&
        Objects.equals(this.updateBy, openAppSecret.updateBy) &&
        Objects.equals(this.updateTime, openAppSecret.updateTime) &&
        Objects.equals(this.remark, openAppSecret.remark) &&
        Objects.equals(this.tenantId, openAppSecret.tenantId) &&
        Objects.equals(this.params, openAppSecret.params) &&
        Objects.equals(this.id, openAppSecret.id) &&
        Objects.equals(this.appId, openAppSecret.appId) &&
        Objects.equals(this.appKey, openAppSecret.appKey) &&
        Objects.equals(this.appSecret, openAppSecret.appSecret) &&
        Objects.equals(this.keyType, openAppSecret.keyType) &&
        Objects.equals(this.status, openAppSecret.status) &&
        Objects.equals(this.dailyQuota, openAppSecret.dailyQuota) &&
        Objects.equals(this.expireTime, openAppSecret.expireTime) &&
        Objects.equals(this.delFlag, openAppSecret.delFlag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createBy, createTime, updateBy, updateTime, remark, tenantId, params, id, appId, appKey, appSecret, keyType, status, dailyQuota, expireTime, delFlag);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OpenAppSecret {\n");
    sb.append("    createBy: ").append(toIndentedString(createBy)).append("\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("    updateBy: ").append(toIndentedString(updateBy)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("    remark: ").append(toIndentedString(remark)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    params: ").append(toIndentedString(params)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    appId: ").append(toIndentedString(appId)).append("\n");
    sb.append("    appKey: ").append(toIndentedString(appKey)).append("\n");
    sb.append("    appSecret: ").append(toIndentedString(appSecret)).append("\n");
    sb.append("    keyType: ").append(toIndentedString(keyType)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    dailyQuota: ").append(toIndentedString(dailyQuota)).append("\n");
    sb.append("    expireTime: ").append(toIndentedString(expireTime)).append("\n");
    sb.append("    delFlag: ").append(toIndentedString(delFlag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("createBy", "createTime", "updateBy", "updateTime", "remark", "tenantId", "params", "id", "appId", "appKey", "appSecret", "keyType", "status", "dailyQuota", "expireTime", "delFlag"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to OpenAppSecret
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!OpenAppSecret.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in OpenAppSecret is not found in the empty JSON string", OpenAppSecret.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!OpenAppSecret.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `OpenAppSecret` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("createBy") != null && !jsonObj.get("createBy").isJsonNull()) && !jsonObj.get("createBy").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `createBy` to be a primitive type in the JSON string but got `%s`", jsonObj.get("createBy").toString()));
      }
      if ((jsonObj.get("updateBy") != null && !jsonObj.get("updateBy").isJsonNull()) && !jsonObj.get("updateBy").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `updateBy` to be a primitive type in the JSON string but got `%s`", jsonObj.get("updateBy").toString()));
      }
      if ((jsonObj.get("remark") != null && !jsonObj.get("remark").isJsonNull()) && !jsonObj.get("remark").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `remark` to be a primitive type in the JSON string but got `%s`", jsonObj.get("remark").toString()));
      }
      if ((jsonObj.get("appKey") != null && !jsonObj.get("appKey").isJsonNull()) && !jsonObj.get("appKey").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `appKey` to be a primitive type in the JSON string but got `%s`", jsonObj.get("appKey").toString()));
      }
      if ((jsonObj.get("appSecret") != null && !jsonObj.get("appSecret").isJsonNull()) && !jsonObj.get("appSecret").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `appSecret` to be a primitive type in the JSON string but got `%s`", jsonObj.get("appSecret").toString()));
      }
      if ((jsonObj.get("keyType") != null && !jsonObj.get("keyType").isJsonNull()) && !jsonObj.get("keyType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `keyType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("keyType").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      if ((jsonObj.get("delFlag") != null && !jsonObj.get("delFlag").isJsonNull()) && !jsonObj.get("delFlag").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `delFlag` to be a primitive type in the JSON string but got `%s`", jsonObj.get("delFlag").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OpenAppSecret.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OpenAppSecret' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OpenAppSecret> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OpenAppSecret.class));

       return (TypeAdapter<T>) new TypeAdapter<OpenAppSecret>() {
           @Override
           public void write(JsonWriter out, OpenAppSecret value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OpenAppSecret read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of OpenAppSecret given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of OpenAppSecret
   * @throws IOException if the JSON string is invalid with respect to OpenAppSecret
   */
  public static OpenAppSecret fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OpenAppSecret.class);
  }

  /**
   * Convert an instance of OpenAppSecret to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

