/*
开放平台接口文档

开放平台应用管理与API Key服务接口

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package junsong

import (
	"encoding/json"
)

// checks if the TableDataInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TableDataInfo{}

// TableDataInfo struct for TableDataInfo
type TableDataInfo struct {
	Total *int64 `json:"total,omitempty"`
	Rows []interface{} `json:"rows,omitempty"`
	Code *int32 `json:"code,omitempty"`
	Msg *string `json:"msg,omitempty"`
}

// NewTableDataInfo instantiates a new TableDataInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTableDataInfo() *TableDataInfo {
	this := TableDataInfo{}
	return &this
}

// NewTableDataInfoWithDefaults instantiates a new TableDataInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTableDataInfoWithDefaults() *TableDataInfo {
	this := TableDataInfo{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *TableDataInfo) GetTotal() int64 {
	if o == nil || IsNil(o.Total) {
		var ret int64
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableDataInfo) GetTotalOk() (*int64, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *TableDataInfo) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int64 and assigns it to the Total field.
func (o *TableDataInfo) SetTotal(v int64) {
	o.Total = &v
}

// GetRows returns the Rows field value if set, zero value otherwise.
func (o *TableDataInfo) GetRows() []interface{} {
	if o == nil || IsNil(o.Rows) {
		var ret []interface{}
		return ret
	}
	return o.Rows
}

// GetRowsOk returns a tuple with the Rows field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableDataInfo) GetRowsOk() ([]interface{}, bool) {
	if o == nil || IsNil(o.Rows) {
		return nil, false
	}
	return o.Rows, true
}

// HasRows returns a boolean if a field has been set.
func (o *TableDataInfo) HasRows() bool {
	if o != nil && !IsNil(o.Rows) {
		return true
	}

	return false
}

// SetRows gets a reference to the given []interface{} and assigns it to the Rows field.
func (o *TableDataInfo) SetRows(v []interface{}) {
	o.Rows = v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *TableDataInfo) GetCode() int32 {
	if o == nil || IsNil(o.Code) {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableDataInfo) GetCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *TableDataInfo) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *TableDataInfo) SetCode(v int32) {
	o.Code = &v
}

// GetMsg returns the Msg field value if set, zero value otherwise.
func (o *TableDataInfo) GetMsg() string {
	if o == nil || IsNil(o.Msg) {
		var ret string
		return ret
	}
	return *o.Msg
}

// GetMsgOk returns a tuple with the Msg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableDataInfo) GetMsgOk() (*string, bool) {
	if o == nil || IsNil(o.Msg) {
		return nil, false
	}
	return o.Msg, true
}

// HasMsg returns a boolean if a field has been set.
func (o *TableDataInfo) HasMsg() bool {
	if o != nil && !IsNil(o.Msg) {
		return true
	}

	return false
}

// SetMsg gets a reference to the given string and assigns it to the Msg field.
func (o *TableDataInfo) SetMsg(v string) {
	o.Msg = &v
}

func (o TableDataInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TableDataInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.Rows) {
		toSerialize["rows"] = o.Rows
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Msg) {
		toSerialize["msg"] = o.Msg
	}
	return toSerialize, nil
}

type NullableTableDataInfo struct {
	value *TableDataInfo
	isSet bool
}

func (v NullableTableDataInfo) Get() *TableDataInfo {
	return v.value
}

func (v *NullableTableDataInfo) Set(val *TableDataInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableTableDataInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableTableDataInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTableDataInfo(val *TableDataInfo) *NullableTableDataInfo {
	return &NullableTableDataInfo{value: val, isSet: true}
}

func (v NullableTableDataInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTableDataInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


