/*
开放平台接口文档

开放平台应用管理与API Key服务接口

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package junsong

import (
	"encoding/json"
	"time"
)

// checks if the OpenAppSecret type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenAppSecret{}

// OpenAppSecret struct for OpenAppSecret
type OpenAppSecret struct {
	CreateBy *string `json:"createBy,omitempty"`
	CreateTime *time.Time `json:"createTime,omitempty"`
	UpdateBy *string `json:"updateBy,omitempty"`
	UpdateTime *time.Time `json:"updateTime,omitempty"`
	Remark *string `json:"remark,omitempty"`
	TenantId *int64 `json:"tenantId,omitempty"`
	Params map[string]interface{} `json:"params,omitempty"`
	Id *int64 `json:"id,omitempty"`
	AppId *int64 `json:"appId,omitempty"`
	AppKey *string `json:"appKey,omitempty"`
	AppSecret *string `json:"appSecret,omitempty"`
	KeyType *string `json:"keyType,omitempty"`
	Status *string `json:"status,omitempty"`
	DailyQuota *int32 `json:"dailyQuota,omitempty"`
	ExpireTime *time.Time `json:"expireTime,omitempty"`
	DelFlag *string `json:"delFlag,omitempty"`
}

// NewOpenAppSecret instantiates a new OpenAppSecret object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenAppSecret() *OpenAppSecret {
	this := OpenAppSecret{}
	return &this
}

// NewOpenAppSecretWithDefaults instantiates a new OpenAppSecret object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenAppSecretWithDefaults() *OpenAppSecret {
	this := OpenAppSecret{}
	return &this
}

// GetCreateBy returns the CreateBy field value if set, zero value otherwise.
func (o *OpenAppSecret) GetCreateBy() string {
	if o == nil || IsNil(o.CreateBy) {
		var ret string
		return ret
	}
	return *o.CreateBy
}

// GetCreateByOk returns a tuple with the CreateBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenAppSecret) GetCreateByOk() (*string, bool) {
	if o == nil || IsNil(o.CreateBy) {
		return nil, false
	}
	return o.CreateBy, true
}

// HasCreateBy returns a boolean if a field has been set.
func (o *OpenAppSecret) HasCreateBy() bool {
	if o != nil && !IsNil(o.CreateBy) {
		return true
	}

	return false
}

// SetCreateBy gets a reference to the given string and assigns it to the CreateBy field.
func (o *OpenAppSecret) SetCreateBy(v string) {
	o.CreateBy = &v
}

// GetCreateTime returns the CreateTime field value if set, zero value otherwise.
func (o *OpenAppSecret) GetCreateTime() time.Time {
	if o == nil || IsNil(o.CreateTime) {
		var ret time.Time
		return ret
	}
	return *o.CreateTime
}

// GetCreateTimeOk returns a tuple with the CreateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenAppSecret) GetCreateTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreateTime) {
		return nil, false
	}
	return o.CreateTime, true
}

// HasCreateTime returns a boolean if a field has been set.
func (o *OpenAppSecret) HasCreateTime() bool {
	if o != nil && !IsNil(o.CreateTime) {
		return true
	}

	return false
}

// SetCreateTime gets a reference to the given time.Time and assigns it to the CreateTime field.
func (o *OpenAppSecret) SetCreateTime(v time.Time) {
	o.CreateTime = &v
}

// GetUpdateBy returns the UpdateBy field value if set, zero value otherwise.
func (o *OpenAppSecret) GetUpdateBy() string {
	if o == nil || IsNil(o.UpdateBy) {
		var ret string
		return ret
	}
	return *o.UpdateBy
}

// GetUpdateByOk returns a tuple with the UpdateBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenAppSecret) GetUpdateByOk() (*string, bool) {
	if o == nil || IsNil(o.UpdateBy) {
		return nil, false
	}
	return o.UpdateBy, true
}

// HasUpdateBy returns a boolean if a field has been set.
func (o *OpenAppSecret) HasUpdateBy() bool {
	if o != nil && !IsNil(o.UpdateBy) {
		return true
	}

	return false
}

// SetUpdateBy gets a reference to the given string and assigns it to the UpdateBy field.
func (o *OpenAppSecret) SetUpdateBy(v string) {
	o.UpdateBy = &v
}

// GetUpdateTime returns the UpdateTime field value if set, zero value otherwise.
func (o *OpenAppSecret) GetUpdateTime() time.Time {
	if o == nil || IsNil(o.UpdateTime) {
		var ret time.Time
		return ret
	}
	return *o.UpdateTime
}

// GetUpdateTimeOk returns a tuple with the UpdateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenAppSecret) GetUpdateTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdateTime) {
		return nil, false
	}
	return o.UpdateTime, true
}

// HasUpdateTime returns a boolean if a field has been set.
func (o *OpenAppSecret) HasUpdateTime() bool {
	if o != nil && !IsNil(o.UpdateTime) {
		return true
	}

	return false
}

// SetUpdateTime gets a reference to the given time.Time and assigns it to the UpdateTime field.
func (o *OpenAppSecret) SetUpdateTime(v time.Time) {
	o.UpdateTime = &v
}

// GetRemark returns the Remark field value if set, zero value otherwise.
func (o *OpenAppSecret) GetRemark() string {
	if o == nil || IsNil(o.Remark) {
		var ret string
		return ret
	}
	return *o.Remark
}

// GetRemarkOk returns a tuple with the Remark field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenAppSecret) GetRemarkOk() (*string, bool) {
	if o == nil || IsNil(o.Remark) {
		return nil, false
	}
	return o.Remark, true
}

// HasRemark returns a boolean if a field has been set.
func (o *OpenAppSecret) HasRemark() bool {
	if o != nil && !IsNil(o.Remark) {
		return true
	}

	return false
}

// SetRemark gets a reference to the given string and assigns it to the Remark field.
func (o *OpenAppSecret) SetRemark(v string) {
	o.Remark = &v
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *OpenAppSecret) GetTenantId() int64 {
	if o == nil || IsNil(o.TenantId) {
		var ret int64
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenAppSecret) GetTenantIdOk() (*int64, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *OpenAppSecret) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given int64 and assigns it to the TenantId field.
func (o *OpenAppSecret) SetTenantId(v int64) {
	o.TenantId = &v
}

// GetParams returns the Params field value if set, zero value otherwise.
func (o *OpenAppSecret) GetParams() map[string]interface{} {
	if o == nil || IsNil(o.Params) {
		var ret map[string]interface{}
		return ret
	}
	return o.Params
}

// GetParamsOk returns a tuple with the Params field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenAppSecret) GetParamsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Params) {
		return map[string]interface{}{}, false
	}
	return o.Params, true
}

// HasParams returns a boolean if a field has been set.
func (o *OpenAppSecret) HasParams() bool {
	if o != nil && !IsNil(o.Params) {
		return true
	}

	return false
}

// SetParams gets a reference to the given map[string]interface{} and assigns it to the Params field.
func (o *OpenAppSecret) SetParams(v map[string]interface{}) {
	o.Params = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *OpenAppSecret) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenAppSecret) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *OpenAppSecret) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *OpenAppSecret) SetId(v int64) {
	o.Id = &v
}

// GetAppId returns the AppId field value if set, zero value otherwise.
func (o *OpenAppSecret) GetAppId() int64 {
	if o == nil || IsNil(o.AppId) {
		var ret int64
		return ret
	}
	return *o.AppId
}

// GetAppIdOk returns a tuple with the AppId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenAppSecret) GetAppIdOk() (*int64, bool) {
	if o == nil || IsNil(o.AppId) {
		return nil, false
	}
	return o.AppId, true
}

// HasAppId returns a boolean if a field has been set.
func (o *OpenAppSecret) HasAppId() bool {
	if o != nil && !IsNil(o.AppId) {
		return true
	}

	return false
}

// SetAppId gets a reference to the given int64 and assigns it to the AppId field.
func (o *OpenAppSecret) SetAppId(v int64) {
	o.AppId = &v
}

// GetAppKey returns the AppKey field value if set, zero value otherwise.
func (o *OpenAppSecret) GetAppKey() string {
	if o == nil || IsNil(o.AppKey) {
		var ret string
		return ret
	}
	return *o.AppKey
}

// GetAppKeyOk returns a tuple with the AppKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenAppSecret) GetAppKeyOk() (*string, bool) {
	if o == nil || IsNil(o.AppKey) {
		return nil, false
	}
	return o.AppKey, true
}

// HasAppKey returns a boolean if a field has been set.
func (o *OpenAppSecret) HasAppKey() bool {
	if o != nil && !IsNil(o.AppKey) {
		return true
	}

	return false
}

// SetAppKey gets a reference to the given string and assigns it to the AppKey field.
func (o *OpenAppSecret) SetAppKey(v string) {
	o.AppKey = &v
}

// GetAppSecret returns the AppSecret field value if set, zero value otherwise.
func (o *OpenAppSecret) GetAppSecret() string {
	if o == nil || IsNil(o.AppSecret) {
		var ret string
		return ret
	}
	return *o.AppSecret
}

// GetAppSecretOk returns a tuple with the AppSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenAppSecret) GetAppSecretOk() (*string, bool) {
	if o == nil || IsNil(o.AppSecret) {
		return nil, false
	}
	return o.AppSecret, true
}

// HasAppSecret returns a boolean if a field has been set.
func (o *OpenAppSecret) HasAppSecret() bool {
	if o != nil && !IsNil(o.AppSecret) {
		return true
	}

	return false
}

// SetAppSecret gets a reference to the given string and assigns it to the AppSecret field.
func (o *OpenAppSecret) SetAppSecret(v string) {
	o.AppSecret = &v
}

// GetKeyType returns the KeyType field value if set, zero value otherwise.
func (o *OpenAppSecret) GetKeyType() string {
	if o == nil || IsNil(o.KeyType) {
		var ret string
		return ret
	}
	return *o.KeyType
}

// GetKeyTypeOk returns a tuple with the KeyType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenAppSecret) GetKeyTypeOk() (*string, bool) {
	if o == nil || IsNil(o.KeyType) {
		return nil, false
	}
	return o.KeyType, true
}

// HasKeyType returns a boolean if a field has been set.
func (o *OpenAppSecret) HasKeyType() bool {
	if o != nil && !IsNil(o.KeyType) {
		return true
	}

	return false
}

// SetKeyType gets a reference to the given string and assigns it to the KeyType field.
func (o *OpenAppSecret) SetKeyType(v string) {
	o.KeyType = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *OpenAppSecret) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenAppSecret) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *OpenAppSecret) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *OpenAppSecret) SetStatus(v string) {
	o.Status = &v
}

// GetDailyQuota returns the DailyQuota field value if set, zero value otherwise.
func (o *OpenAppSecret) GetDailyQuota() int32 {
	if o == nil || IsNil(o.DailyQuota) {
		var ret int32
		return ret
	}
	return *o.DailyQuota
}

// GetDailyQuotaOk returns a tuple with the DailyQuota field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenAppSecret) GetDailyQuotaOk() (*int32, bool) {
	if o == nil || IsNil(o.DailyQuota) {
		return nil, false
	}
	return o.DailyQuota, true
}

// HasDailyQuota returns a boolean if a field has been set.
func (o *OpenAppSecret) HasDailyQuota() bool {
	if o != nil && !IsNil(o.DailyQuota) {
		return true
	}

	return false
}

// SetDailyQuota gets a reference to the given int32 and assigns it to the DailyQuota field.
func (o *OpenAppSecret) SetDailyQuota(v int32) {
	o.DailyQuota = &v
}

// GetExpireTime returns the ExpireTime field value if set, zero value otherwise.
func (o *OpenAppSecret) GetExpireTime() time.Time {
	if o == nil || IsNil(o.ExpireTime) {
		var ret time.Time
		return ret
	}
	return *o.ExpireTime
}

// GetExpireTimeOk returns a tuple with the ExpireTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenAppSecret) GetExpireTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpireTime) {
		return nil, false
	}
	return o.ExpireTime, true
}

// HasExpireTime returns a boolean if a field has been set.
func (o *OpenAppSecret) HasExpireTime() bool {
	if o != nil && !IsNil(o.ExpireTime) {
		return true
	}

	return false
}

// SetExpireTime gets a reference to the given time.Time and assigns it to the ExpireTime field.
func (o *OpenAppSecret) SetExpireTime(v time.Time) {
	o.ExpireTime = &v
}

// GetDelFlag returns the DelFlag field value if set, zero value otherwise.
func (o *OpenAppSecret) GetDelFlag() string {
	if o == nil || IsNil(o.DelFlag) {
		var ret string
		return ret
	}
	return *o.DelFlag
}

// GetDelFlagOk returns a tuple with the DelFlag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenAppSecret) GetDelFlagOk() (*string, bool) {
	if o == nil || IsNil(o.DelFlag) {
		return nil, false
	}
	return o.DelFlag, true
}

// HasDelFlag returns a boolean if a field has been set.
func (o *OpenAppSecret) HasDelFlag() bool {
	if o != nil && !IsNil(o.DelFlag) {
		return true
	}

	return false
}

// SetDelFlag gets a reference to the given string and assigns it to the DelFlag field.
func (o *OpenAppSecret) SetDelFlag(v string) {
	o.DelFlag = &v
}

func (o OpenAppSecret) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenAppSecret) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreateBy) {
		toSerialize["createBy"] = o.CreateBy
	}
	if !IsNil(o.CreateTime) {
		toSerialize["createTime"] = o.CreateTime
	}
	if !IsNil(o.UpdateBy) {
		toSerialize["updateBy"] = o.UpdateBy
	}
	if !IsNil(o.UpdateTime) {
		toSerialize["updateTime"] = o.UpdateTime
	}
	if !IsNil(o.Remark) {
		toSerialize["remark"] = o.Remark
	}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.Params) {
		toSerialize["params"] = o.Params
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.AppId) {
		toSerialize["appId"] = o.AppId
	}
	if !IsNil(o.AppKey) {
		toSerialize["appKey"] = o.AppKey
	}
	if !IsNil(o.AppSecret) {
		toSerialize["appSecret"] = o.AppSecret
	}
	if !IsNil(o.KeyType) {
		toSerialize["keyType"] = o.KeyType
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.DailyQuota) {
		toSerialize["dailyQuota"] = o.DailyQuota
	}
	if !IsNil(o.ExpireTime) {
		toSerialize["expireTime"] = o.ExpireTime
	}
	if !IsNil(o.DelFlag) {
		toSerialize["delFlag"] = o.DelFlag
	}
	return toSerialize, nil
}

type NullableOpenAppSecret struct {
	value *OpenAppSecret
	isSet bool
}

func (v NullableOpenAppSecret) Get() *OpenAppSecret {
	return v.value
}

func (v *NullableOpenAppSecret) Set(val *OpenAppSecret) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenAppSecret) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenAppSecret) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenAppSecret(val *OpenAppSecret) *NullableOpenAppSecret {
	return &NullableOpenAppSecret{value: val, isSet: true}
}

func (v NullableOpenAppSecret) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenAppSecret) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


