/*
开放平台接口文档

开放平台应用管理与API Key服务接口

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package junsong

import (
	"encoding/json"
	"time"
)

// checks if the OpenApp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenApp{}

// OpenApp struct for OpenApp
type OpenApp struct {
	CreateBy *string `json:"createBy,omitempty"`
	CreateTime *time.Time `json:"createTime,omitempty"`
	UpdateBy *string `json:"updateBy,omitempty"`
	UpdateTime *time.Time `json:"updateTime,omitempty"`
	Remark *string `json:"remark,omitempty"`
	TenantId *int64 `json:"tenantId,omitempty"`
	Params map[string]interface{} `json:"params,omitempty"`
	Id *int64 `json:"id,omitempty"`
	AppName *string `json:"appName,omitempty"`
	AppType *string `json:"appType,omitempty"`
	Description *string `json:"description,omitempty"`
	WebsiteUrl *string `json:"websiteUrl,omitempty"`
	CallbackUrl *string `json:"callbackUrl,omitempty"`
	ContactName *string `json:"contactName,omitempty"`
	ContactPhone *string `json:"contactPhone,omitempty"`
	ContactEmail *string `json:"contactEmail,omitempty"`
	Status *string `json:"status,omitempty"`
	RejectReason *string `json:"rejectReason,omitempty"`
	DelFlag *string `json:"delFlag,omitempty"`
}

// NewOpenApp instantiates a new OpenApp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenApp() *OpenApp {
	this := OpenApp{}
	return &this
}

// NewOpenAppWithDefaults instantiates a new OpenApp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenAppWithDefaults() *OpenApp {
	this := OpenApp{}
	return &this
}

// GetCreateBy returns the CreateBy field value if set, zero value otherwise.
func (o *OpenApp) GetCreateBy() string {
	if o == nil || IsNil(o.CreateBy) {
		var ret string
		return ret
	}
	return *o.CreateBy
}

// GetCreateByOk returns a tuple with the CreateBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenApp) GetCreateByOk() (*string, bool) {
	if o == nil || IsNil(o.CreateBy) {
		return nil, false
	}
	return o.CreateBy, true
}

// HasCreateBy returns a boolean if a field has been set.
func (o *OpenApp) HasCreateBy() bool {
	if o != nil && !IsNil(o.CreateBy) {
		return true
	}

	return false
}

// SetCreateBy gets a reference to the given string and assigns it to the CreateBy field.
func (o *OpenApp) SetCreateBy(v string) {
	o.CreateBy = &v
}

// GetCreateTime returns the CreateTime field value if set, zero value otherwise.
func (o *OpenApp) GetCreateTime() time.Time {
	if o == nil || IsNil(o.CreateTime) {
		var ret time.Time
		return ret
	}
	return *o.CreateTime
}

// GetCreateTimeOk returns a tuple with the CreateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenApp) GetCreateTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreateTime) {
		return nil, false
	}
	return o.CreateTime, true
}

// HasCreateTime returns a boolean if a field has been set.
func (o *OpenApp) HasCreateTime() bool {
	if o != nil && !IsNil(o.CreateTime) {
		return true
	}

	return false
}

// SetCreateTime gets a reference to the given time.Time and assigns it to the CreateTime field.
func (o *OpenApp) SetCreateTime(v time.Time) {
	o.CreateTime = &v
}

// GetUpdateBy returns the UpdateBy field value if set, zero value otherwise.
func (o *OpenApp) GetUpdateBy() string {
	if o == nil || IsNil(o.UpdateBy) {
		var ret string
		return ret
	}
	return *o.UpdateBy
}

// GetUpdateByOk returns a tuple with the UpdateBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenApp) GetUpdateByOk() (*string, bool) {
	if o == nil || IsNil(o.UpdateBy) {
		return nil, false
	}
	return o.UpdateBy, true
}

// HasUpdateBy returns a boolean if a field has been set.
func (o *OpenApp) HasUpdateBy() bool {
	if o != nil && !IsNil(o.UpdateBy) {
		return true
	}

	return false
}

// SetUpdateBy gets a reference to the given string and assigns it to the UpdateBy field.
func (o *OpenApp) SetUpdateBy(v string) {
	o.UpdateBy = &v
}

// GetUpdateTime returns the UpdateTime field value if set, zero value otherwise.
func (o *OpenApp) GetUpdateTime() time.Time {
	if o == nil || IsNil(o.UpdateTime) {
		var ret time.Time
		return ret
	}
	return *o.UpdateTime
}

// GetUpdateTimeOk returns a tuple with the UpdateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenApp) GetUpdateTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdateTime) {
		return nil, false
	}
	return o.UpdateTime, true
}

// HasUpdateTime returns a boolean if a field has been set.
func (o *OpenApp) HasUpdateTime() bool {
	if o != nil && !IsNil(o.UpdateTime) {
		return true
	}

	return false
}

// SetUpdateTime gets a reference to the given time.Time and assigns it to the UpdateTime field.
func (o *OpenApp) SetUpdateTime(v time.Time) {
	o.UpdateTime = &v
}

// GetRemark returns the Remark field value if set, zero value otherwise.
func (o *OpenApp) GetRemark() string {
	if o == nil || IsNil(o.Remark) {
		var ret string
		return ret
	}
	return *o.Remark
}

// GetRemarkOk returns a tuple with the Remark field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenApp) GetRemarkOk() (*string, bool) {
	if o == nil || IsNil(o.Remark) {
		return nil, false
	}
	return o.Remark, true
}

// HasRemark returns a boolean if a field has been set.
func (o *OpenApp) HasRemark() bool {
	if o != nil && !IsNil(o.Remark) {
		return true
	}

	return false
}

// SetRemark gets a reference to the given string and assigns it to the Remark field.
func (o *OpenApp) SetRemark(v string) {
	o.Remark = &v
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *OpenApp) GetTenantId() int64 {
	if o == nil || IsNil(o.TenantId) {
		var ret int64
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenApp) GetTenantIdOk() (*int64, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *OpenApp) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given int64 and assigns it to the TenantId field.
func (o *OpenApp) SetTenantId(v int64) {
	o.TenantId = &v
}

// GetParams returns the Params field value if set, zero value otherwise.
func (o *OpenApp) GetParams() map[string]interface{} {
	if o == nil || IsNil(o.Params) {
		var ret map[string]interface{}
		return ret
	}
	return o.Params
}

// GetParamsOk returns a tuple with the Params field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenApp) GetParamsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Params) {
		return map[string]interface{}{}, false
	}
	return o.Params, true
}

// HasParams returns a boolean if a field has been set.
func (o *OpenApp) HasParams() bool {
	if o != nil && !IsNil(o.Params) {
		return true
	}

	return false
}

// SetParams gets a reference to the given map[string]interface{} and assigns it to the Params field.
func (o *OpenApp) SetParams(v map[string]interface{}) {
	o.Params = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *OpenApp) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenApp) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *OpenApp) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *OpenApp) SetId(v int64) {
	o.Id = &v
}

// GetAppName returns the AppName field value if set, zero value otherwise.
func (o *OpenApp) GetAppName() string {
	if o == nil || IsNil(o.AppName) {
		var ret string
		return ret
	}
	return *o.AppName
}

// GetAppNameOk returns a tuple with the AppName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenApp) GetAppNameOk() (*string, bool) {
	if o == nil || IsNil(o.AppName) {
		return nil, false
	}
	return o.AppName, true
}

// HasAppName returns a boolean if a field has been set.
func (o *OpenApp) HasAppName() bool {
	if o != nil && !IsNil(o.AppName) {
		return true
	}

	return false
}

// SetAppName gets a reference to the given string and assigns it to the AppName field.
func (o *OpenApp) SetAppName(v string) {
	o.AppName = &v
}

// GetAppType returns the AppType field value if set, zero value otherwise.
func (o *OpenApp) GetAppType() string {
	if o == nil || IsNil(o.AppType) {
		var ret string
		return ret
	}
	return *o.AppType
}

// GetAppTypeOk returns a tuple with the AppType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenApp) GetAppTypeOk() (*string, bool) {
	if o == nil || IsNil(o.AppType) {
		return nil, false
	}
	return o.AppType, true
}

// HasAppType returns a boolean if a field has been set.
func (o *OpenApp) HasAppType() bool {
	if o != nil && !IsNil(o.AppType) {
		return true
	}

	return false
}

// SetAppType gets a reference to the given string and assigns it to the AppType field.
func (o *OpenApp) SetAppType(v string) {
	o.AppType = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *OpenApp) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenApp) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *OpenApp) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *OpenApp) SetDescription(v string) {
	o.Description = &v
}

// GetWebsiteUrl returns the WebsiteUrl field value if set, zero value otherwise.
func (o *OpenApp) GetWebsiteUrl() string {
	if o == nil || IsNil(o.WebsiteUrl) {
		var ret string
		return ret
	}
	return *o.WebsiteUrl
}

// GetWebsiteUrlOk returns a tuple with the WebsiteUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenApp) GetWebsiteUrlOk() (*string, bool) {
	if o == nil || IsNil(o.WebsiteUrl) {
		return nil, false
	}
	return o.WebsiteUrl, true
}

// HasWebsiteUrl returns a boolean if a field has been set.
func (o *OpenApp) HasWebsiteUrl() bool {
	if o != nil && !IsNil(o.WebsiteUrl) {
		return true
	}

	return false
}

// SetWebsiteUrl gets a reference to the given string and assigns it to the WebsiteUrl field.
func (o *OpenApp) SetWebsiteUrl(v string) {
	o.WebsiteUrl = &v
}

// GetCallbackUrl returns the CallbackUrl field value if set, zero value otherwise.
func (o *OpenApp) GetCallbackUrl() string {
	if o == nil || IsNil(o.CallbackUrl) {
		var ret string
		return ret
	}
	return *o.CallbackUrl
}

// GetCallbackUrlOk returns a tuple with the CallbackUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenApp) GetCallbackUrlOk() (*string, bool) {
	if o == nil || IsNil(o.CallbackUrl) {
		return nil, false
	}
	return o.CallbackUrl, true
}

// HasCallbackUrl returns a boolean if a field has been set.
func (o *OpenApp) HasCallbackUrl() bool {
	if o != nil && !IsNil(o.CallbackUrl) {
		return true
	}

	return false
}

// SetCallbackUrl gets a reference to the given string and assigns it to the CallbackUrl field.
func (o *OpenApp) SetCallbackUrl(v string) {
	o.CallbackUrl = &v
}

// GetContactName returns the ContactName field value if set, zero value otherwise.
func (o *OpenApp) GetContactName() string {
	if o == nil || IsNil(o.ContactName) {
		var ret string
		return ret
	}
	return *o.ContactName
}

// GetContactNameOk returns a tuple with the ContactName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenApp) GetContactNameOk() (*string, bool) {
	if o == nil || IsNil(o.ContactName) {
		return nil, false
	}
	return o.ContactName, true
}

// HasContactName returns a boolean if a field has been set.
func (o *OpenApp) HasContactName() bool {
	if o != nil && !IsNil(o.ContactName) {
		return true
	}

	return false
}

// SetContactName gets a reference to the given string and assigns it to the ContactName field.
func (o *OpenApp) SetContactName(v string) {
	o.ContactName = &v
}

// GetContactPhone returns the ContactPhone field value if set, zero value otherwise.
func (o *OpenApp) GetContactPhone() string {
	if o == nil || IsNil(o.ContactPhone) {
		var ret string
		return ret
	}
	return *o.ContactPhone
}

// GetContactPhoneOk returns a tuple with the ContactPhone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenApp) GetContactPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.ContactPhone) {
		return nil, false
	}
	return o.ContactPhone, true
}

// HasContactPhone returns a boolean if a field has been set.
func (o *OpenApp) HasContactPhone() bool {
	if o != nil && !IsNil(o.ContactPhone) {
		return true
	}

	return false
}

// SetContactPhone gets a reference to the given string and assigns it to the ContactPhone field.
func (o *OpenApp) SetContactPhone(v string) {
	o.ContactPhone = &v
}

// GetContactEmail returns the ContactEmail field value if set, zero value otherwise.
func (o *OpenApp) GetContactEmail() string {
	if o == nil || IsNil(o.ContactEmail) {
		var ret string
		return ret
	}
	return *o.ContactEmail
}

// GetContactEmailOk returns a tuple with the ContactEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenApp) GetContactEmailOk() (*string, bool) {
	if o == nil || IsNil(o.ContactEmail) {
		return nil, false
	}
	return o.ContactEmail, true
}

// HasContactEmail returns a boolean if a field has been set.
func (o *OpenApp) HasContactEmail() bool {
	if o != nil && !IsNil(o.ContactEmail) {
		return true
	}

	return false
}

// SetContactEmail gets a reference to the given string and assigns it to the ContactEmail field.
func (o *OpenApp) SetContactEmail(v string) {
	o.ContactEmail = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *OpenApp) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenApp) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *OpenApp) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *OpenApp) SetStatus(v string) {
	o.Status = &v
}

// GetRejectReason returns the RejectReason field value if set, zero value otherwise.
func (o *OpenApp) GetRejectReason() string {
	if o == nil || IsNil(o.RejectReason) {
		var ret string
		return ret
	}
	return *o.RejectReason
}

// GetRejectReasonOk returns a tuple with the RejectReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenApp) GetRejectReasonOk() (*string, bool) {
	if o == nil || IsNil(o.RejectReason) {
		return nil, false
	}
	return o.RejectReason, true
}

// HasRejectReason returns a boolean if a field has been set.
func (o *OpenApp) HasRejectReason() bool {
	if o != nil && !IsNil(o.RejectReason) {
		return true
	}

	return false
}

// SetRejectReason gets a reference to the given string and assigns it to the RejectReason field.
func (o *OpenApp) SetRejectReason(v string) {
	o.RejectReason = &v
}

// GetDelFlag returns the DelFlag field value if set, zero value otherwise.
func (o *OpenApp) GetDelFlag() string {
	if o == nil || IsNil(o.DelFlag) {
		var ret string
		return ret
	}
	return *o.DelFlag
}

// GetDelFlagOk returns a tuple with the DelFlag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenApp) GetDelFlagOk() (*string, bool) {
	if o == nil || IsNil(o.DelFlag) {
		return nil, false
	}
	return o.DelFlag, true
}

// HasDelFlag returns a boolean if a field has been set.
func (o *OpenApp) HasDelFlag() bool {
	if o != nil && !IsNil(o.DelFlag) {
		return true
	}

	return false
}

// SetDelFlag gets a reference to the given string and assigns it to the DelFlag field.
func (o *OpenApp) SetDelFlag(v string) {
	o.DelFlag = &v
}

func (o OpenApp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenApp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreateBy) {
		toSerialize["createBy"] = o.CreateBy
	}
	if !IsNil(o.CreateTime) {
		toSerialize["createTime"] = o.CreateTime
	}
	if !IsNil(o.UpdateBy) {
		toSerialize["updateBy"] = o.UpdateBy
	}
	if !IsNil(o.UpdateTime) {
		toSerialize["updateTime"] = o.UpdateTime
	}
	if !IsNil(o.Remark) {
		toSerialize["remark"] = o.Remark
	}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.Params) {
		toSerialize["params"] = o.Params
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.AppName) {
		toSerialize["appName"] = o.AppName
	}
	if !IsNil(o.AppType) {
		toSerialize["appType"] = o.AppType
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.WebsiteUrl) {
		toSerialize["websiteUrl"] = o.WebsiteUrl
	}
	if !IsNil(o.CallbackUrl) {
		toSerialize["callbackUrl"] = o.CallbackUrl
	}
	if !IsNil(o.ContactName) {
		toSerialize["contactName"] = o.ContactName
	}
	if !IsNil(o.ContactPhone) {
		toSerialize["contactPhone"] = o.ContactPhone
	}
	if !IsNil(o.ContactEmail) {
		toSerialize["contactEmail"] = o.ContactEmail
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.RejectReason) {
		toSerialize["rejectReason"] = o.RejectReason
	}
	if !IsNil(o.DelFlag) {
		toSerialize["delFlag"] = o.DelFlag
	}
	return toSerialize, nil
}

type NullableOpenApp struct {
	value *OpenApp
	isSet bool
}

func (v NullableOpenApp) Get() *OpenApp {
	return v.value
}

func (v *NullableOpenApp) Set(val *OpenApp) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenApp) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenApp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenApp(val *OpenApp) *NullableOpenApp {
	return &NullableOpenApp{value: val, isSet: true}
}

func (v NullableOpenApp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenApp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


