# coding: utf-8

"""
    开放平台接口文档

    开放平台应用管理与API Key服务接口

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from junsong_open_sdk.models.table_data_info import TableDataInfo

class TestTableDataInfo(unittest.TestCase):
    """TableDataInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TableDataInfo:
        """Test TableDataInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TableDataInfo`
        """
        model = TableDataInfo()
        if include_optional:
            return TableDataInfo(
                total = 56,
                rows = [
                    null
                    ],
                code = 56,
                msg = ''
            )
        else:
            return TableDataInfo(
        )
        """

    def testTableDataInfo(self):
        """Test TableDataInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
