# coding: utf-8

"""
    开放平台接口文档

    开放平台应用管理与API Key服务接口

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from junsong_open_sdk.models.open_app import OpenApp

class TestOpenApp(unittest.TestCase):
    """OpenApp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OpenApp:
        """Test OpenApp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OpenApp`
        """
        model = OpenApp()
        if include_optional:
            return OpenApp(
                create_by = '',
                create_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                update_by = '',
                update_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                remark = '',
                tenant_id = 56,
                params = {
                    'key' : null
                    },
                id = 56,
                app_name = '',
                app_type = '',
                description = '',
                website_url = '',
                callback_url = '',
                contact_name = '',
                contact_phone = '',
                contact_email = '',
                status = '',
                reject_reason = '',
                del_flag = ''
            )
        else:
            return OpenApp(
        )
        """

    def testOpenApp(self):
        """Test OpenApp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
