# coding: utf-8

"""
    开放平台接口文档

    开放平台应用管理与API Key服务接口

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from junsong_open_sdk.models.open_app_secret import OpenAppSecret

class TestOpenAppSecret(unittest.TestCase):
    """OpenAppSecret unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OpenAppSecret:
        """Test OpenAppSecret
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OpenAppSecret`
        """
        model = OpenAppSecret()
        if include_optional:
            return OpenAppSecret(
                create_by = '',
                create_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                update_by = '',
                update_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                remark = '',
                tenant_id = 56,
                params = {
                    'key' : null
                    },
                id = 56,
                app_id = 56,
                app_key = '',
                app_secret = '',
                key_type = '',
                status = '',
                daily_quota = 56,
                expire_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                del_flag = ''
            )
        else:
            return OpenAppSecret(
        )
        """

    def testOpenAppSecret(self):
        """Test OpenAppSecret"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
