# coding: utf-8

"""
    开放平台接口文档

    开放平台应用管理与API Key服务接口

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from junsong_open_sdk.api.open_app_controller_api import OpenAppControllerApi


class TestOpenAppControllerApi(unittest.TestCase):
    """OpenAppControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OpenAppControllerApi()

    def tearDown(self) -> None:
        pass

    def test_add(self) -> None:
        """Test case for add

        """
        pass

    def test_approve(self) -> None:
        """Test case for approve

        """
        pass

    def test_change_key_status(self) -> None:
        """Test case for change_key_status

        """
        pass

    def test_edit(self) -> None:
        """Test case for edit

        """
        pass

    def test_export(self) -> None:
        """Test case for export

        """
        pass

    def test_get_info(self) -> None:
        """Test case for get_info

        """
        pass

    def test_list(self) -> None:
        """Test case for list

        """
        pass

    def test_list_all_keys(self) -> None:
        """Test case for list_all_keys

        """
        pass

    def test_list_keys(self) -> None:
        """Test case for list_keys

        """
        pass

    def test_reject(self) -> None:
        """Test case for reject

        """
        pass

    def test_remove(self) -> None:
        """Test case for remove

        """
        pass


if __name__ == '__main__':
    unittest.main()
