# coding: utf-8

"""
    开放平台接口文档

    开放平台应用管理与API Key服务接口

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from junsong_open_sdk.api.open_internal_controller_api import OpenInternalControllerApi


class TestOpenInternalControllerApi(unittest.TestCase):
    """OpenInternalControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OpenInternalControllerApi()

    def tearDown(self) -> None:
        pass

    def test_get_by_app_key(self) -> None:
        """Test case for get_by_app_key

        """
        pass


if __name__ == '__main__':
    unittest.main()
