<template>
  <view class="page" v-if="authorized">
    <view class="hero"><text class="eyebrow">会员服务 · {{ deptName }}</text><text class="title">购买退货/退款</text><text class="subtitle">原购买单不改写，支持跨核算周期办理</text></view>
    <view class="actions"><button v-if="can('add')" class="primary" @tap="openCreate">＋ 新建退货单</button><button @tap="load">刷新</button></view>
    <view class="card" v-for="row in rows" :key="row.returnId"><view class="row-head"><text class="name">{{ row.returnNo }}</text><text class="status">{{ statusText(row.status) }}</text></view><text class="meta">原购买单：{{ row.purchaseId }} · {{ row.customerName || '未登记顾客' }}</text><text class="amount">退款 ¥{{ money(row.refundAmount) }}</text><button v-if="row.status === 'DRAFT' && can('complete')" class="complete" @tap="complete(row)">完成退货</button></view>
    <view class="empty" v-if="!rows.length">暂无退货记录</view>
    <view class="mask" v-if="panel" @tap="panel=''"><view class="panel" @tap.stop><view class="panel-title">新建退货/退款单</view><view class="field full"><text>原购买单</text><picker :range="purchaseOptions" range-key="label" :value="purchaseIndex" @change="selectPurchase"><view class="control">{{ purchaseOptions[purchaseIndex]?.label || '请选择原购买单' }}</view></picker></view><view class="field full"><text>退货办理核算周期</text><picker :range="periods" range-key="label" :value="periodIndex" @change="selectPeriod"><view class="control">{{ periods[periodIndex]?.label || '请选择当前机构周期' }}</view></picker></view><view class="section-title">退货明细（已领取数量也允许退）</view><view class="item-box" v-for="item in returnItems" :key="item.itemId"><text class="product">{{ item.productNameSnapshot }}</text><view class="limits">原正品 {{ quantity(item.purchaseQuantity) }} · 原赠品 {{ quantity(item.giftQuantity) }}</view><view class="form-grid"><view class="field"><text>退正品</text><input v-model="item.returnSaleQuantity" type="digit" placeholder="0.000" @input="limit(item,'returnSaleQuantity',3)" /></view><view class="field"><text>退赠品</text><input v-model="item.returnGiftQuantity" type="digit" placeholder="0.000" @input="limit(item,'returnGiftQuantity',3)" /></view></view></view><view class="field full"><text>退货原因</text><textarea v-model="form.reason" placeholder="请填写退货原因" /></view><button class="primary wide" @tap="submit">保存退货单</button></view></view>
  </view>
</template>
<script>
import { request } from '@/api/index.js'
import { createMemberPurchaseReturn, listMemberPurchaseReturns } from '@/api/memberPurchaseReturn.js'
import { hasActionPermission, requireModulePermission } from '@/utils/permission.js'
import { workContext } from '@/utils/workContext.js'
export default {
  data() { return { authorized:false, deptId:'', deptName:'', rows:[], periods:[], purchaseOptions:[], purchaseIndex:0, periodIndex:0, returnItems:[], panel:false, form:{purchaseId:'',returnPeriodId:'',reason:''} } },
  onLoad(options) { this.authorized=requireModulePermission('memberPurchaseReturn'); const s=workContext.snapshot(); this.deptId=s.currentDeptId; this.deptName=s.currentDept?.name||s.currentDept?.deptName||'未选择机构'; if(this.authorized){ this.loadOptions(options?.purchaseId); this.load() } },
  methods: {
    can(a){return hasActionPermission('memberPurchaseReturn',a)}, unwrap(r){return r?.rows||r?.data?.rows||r?.data||[]}, quantity(v){return Number(v||0).toFixed(3).replace(/\.0+$/,'').replace(/(\.\d*?)0+$/,'$1')}, money(v){return Number(v||0).toFixed(2)}, statusText(v){return ({DRAFT:'草稿',PENDING:'待审核',APPROVED:'已批准',COMPLETED:'已完成',REFUNDED:'已退款',CANCELLED:'已作废'})[v]||v||'-'}, periodLabel(v){return `${v.periodNo||v.periodId}（${this.dateText(v.startTime)} 至 ${v.endTime?this.dateText(v.endTime):'当前'}）`}, dateText(v){return v?String(v).replace('T',' ').slice(0,19):'-'}, limit(item,key,value,precision){const s=String(value||'').replace(/[^\d.]/g,'').replace(/\.(?=.*\.)/g,'');item[key]=s.includes('.')?s.split('.')[0]+'.'+s.split('.')[1].slice(0,precision):s},
    async load(){const r=await listMemberPurchaseReturns({pageNum:1,pageSize:100,deptId:this.deptId});this.rows=this.unwrap(r)}, async loadOptions(purchaseId){const [periods,purchases]=await Promise.all([request({url:'/finance/accountingPeriod/list',method:'GET',data:{pageNum:1,pageSize:200,deptId:this.deptId}}),request({url:'/member/purchase/list',method:'GET',data:{pageNum:1,pageSize:200,deptId:this.deptId}})]);this.periods=this.unwrap(periods).filter(x=>String(x.deptId)===String(this.deptId)).map(x=>({...x,label:this.periodLabel(x)}));this.purchaseOptions=this.unwrap(purchases).map(x=>({...x,label:`${x.purchaseNo||x.purchaseId} · ${x.customerName||'未登记顾客'}`}));if(purchaseId){const i=this.purchaseOptions.findIndex(x=>String(x.purchaseId)===String(purchaseId));if(i>=0){this.purchaseIndex=i;await this.selectPurchase({detail:{value:i}})}}},
    openCreate(){this.form={purchaseId:'',returnPeriodId:this.periods[0]?.periodId||'',reason:''};this.periodIndex=0;this.returnItems=[];this.panel=true}, async complete(row){try{await new Promise((resolve,reject)=>uni.showModal({title:'操作确认',content:`确认完成退货单 ${row.returnNo||row.returnId} 吗？`,success:r=>r.confirm?resolve(r):reject()}));await request({url:`/member/purchase-return/${row.returnId}/complete`,method:'PUT'});uni.showToast({title:'退货单已完成',icon:'success'});this.load()}catch(e){}}, async selectPurchase(e){this.purchaseIndex=Number(e.detail.value);const p=this.purchaseOptions[this.purchaseIndex];this.form.purchaseId=p?.purchaseId||'';if(!p){this.returnItems=[];return}const r=await request({url:`/member/purchase/${p.purchaseId}`,method:'GET'});const d=r.data||r;this.returnItems=(d.items||[]).map(x=>({...x,returnSaleQuantity:'',returnGiftQuantity:''}))},selectPeriod(e){this.periodIndex=Number(e.detail.value);this.form.returnPeriodId=this.periods[this.periodIndex]?.periodId||''},async submit(){const items=this.returnItems.filter(x=>Number(x.returnSaleQuantity||0)>0||Number(x.returnGiftQuantity||0)).map(x=>({itemId:x.itemId,returnSaleQuantity:Number(x.returnSaleQuantity||0),returnGiftQuantity:Number(x.returnGiftQuantity||0)}));if(!this.form.purchaseId||!this.form.returnPeriodId||!items.length)return uni.showToast({title:'请选择原购买单、办理周期并填写退货数量',icon:'none'});await createMemberPurchaseReturn({...this.form,items,idempotencyKey:`mp-return-${Date.now()}`});uni.showToast({title:'退货单已保存',icon:'success'});this.panel=false;this.load()}
  }
}
</script>
<style scoped>.page{min-height:100vh;background:#f4f7fb;padding:24rpx}.hero{padding:30rpx;background:linear-gradient(135deg,#0b74de,#1456b8);border-radius:22rpx;color:#fff}.eyebrow,.subtitle{display:block;font-size:23rpx;opacity:.82}.title{display:block;margin:8rpx 0;font-size:40rpx;font-weight:700}.actions{display:flex;gap:14rpx;margin:20rpx 0}.actions button,.wide{border:0;border-radius:12rpx;padding:10rpx 24rpx;background:#eef3f8;color:#334155}.primary{background:#0b74de!important;color:#fff!important}.card,.panel{background:#fff;border-radius:18rpx;padding:24rpx;margin-bottom:16rpx;box-shadow:0 8rpx 24rpx rgba(15,23,42,.06)}.row-head{display:flex;justify-content:space-between}.name{font-size:30rpx;font-weight:700}.status{color:#16865a}.meta,.limits{display:block;margin-top:10rpx;color:#64748b;font-size:23rpx}.amount{display:block;margin-top:16rpx;color:#e6535b;font-size:30rpx;font-weight:700}.empty{text-align:center;color:#94a3b8;padding:80rpx}.mask{position:fixed;inset:0;background:rgba(15,23,42,.45);z-index:20;padding:40rpx 24rpx;overflow:auto}.panel{max-height:calc(100vh - 80rpx);overflow:auto}.panel-title{font-size:34rpx;font-weight:700;margin-bottom:20rpx}.field{margin-top:16rpx}.field.full{width:100%}.field text{display:block;color:#475569;font-size:24rpx;margin-bottom:8rpx}.field input,.field textarea,.control{box-sizing:border-box;width:100%;padding:20rpx;border:1rpx solid #dce5f0;border-radius:12rpx;background:#fff}.control{color:#334155;background:#f8fafc}.section-title{margin-top:24rpx;font-weight:700}.item-box{padding:16rpx;margin-top:14rpx;border:1rpx solid #e4ebf3;border-radius:14rpx}.product{font-weight:700}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:16rpx}.wide{width:100%;margin-top:24rpx}</style>
